### ISSUE TITLE
Bug: Alert Message Size

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#100]
## Background

Depending on the data source, alert size can vary.  Before sending to Slack (or any input for that matter), message size should be taken into account and handled appropriately.

## Desired Outcome

For Slack, the message size should be measured prior to sending.  From the [documentation](https://api.slack.com/docs/message-formatting), it mentions:

> For best results, limit the number of characters in the text field to a few thousand bytes at most. Ideally, messages should be short and human-readable, if you need to post longer messages, please consider uploading a snippet instead. (A single message should be no larger than 4,000 bytes.)

**Comment by mime-frame** [comment]
Fixed via https://github.com/airbnb/streamalert/pull/135
