### ISSUE TITLE
Improvement: Slack mrkdwn

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#102]
It seems mrkdwn is supported for Slack message formatting.  This would make the JSON dumped alert look much prettier.

**Comment by jacknagz** [comment]
I did some digging on this, and `mrkdwn` is not normal Markdown.  It's just Slack sugar for basic things like code blocks, bold, and italics.   You have the option of disabling it with the messaging API in case you wanted to literally wrap a message with `*` or `_`
