### ISSUE TITLE
[q3] Feature: Normalization of Consumed Data

### ISSUE THREAD

**Issue by armtash** [airbnb/streamalert#105]
From what I can see, data that is consumed is checked against the logs.json to validate the schema of the consumed data, however no mechanism exists to map data being consumed to a "common" or "standard" format.  Common formats include [CEF](https://www.protect724.hpe.com/docs/DOC-1072) (ArcSight standard) and [CIM](http://docs.splunk.com/Documentation/CIM/4.7.0/User/Overview) (Splunk standard).

Splunk's justification for CIM:
>  CIM helps you to normalize your data to match a common standard, using the same field names and event tags for equivalent events from different sources or vendors.

Mapping data to common format would make things like rule creation and integration with other tools more simplistic.  It could also help with IOC matching in https://github.com/airbnb/streamalert/issues/2.

From a rule creation perspective, rather than having to explicitly match against all possible keys: 

```
def bad_ip_address(rec):
    """Malicious IP Detected"""
    return (
        rec['destip'] == 8.8.8.8 or rec['destination_ip'] == 8.8.8.8 or rec['dst_ip'] == 8.8.8.8
    )
```
you could match against a single standard field (CEF):
```
def bad_ip_address(rec):
    """Malicious IP Detected"""
    return (
        rec['destinationAddress'] == 8.8.8.8
    )
```

**Comment by mime-frame** [comment]
We'll be working on this, this quarter :)

**Comment by armtash** [comment]
Awesome!

**Comment by mime-frame** [comment]
Completed via https://github.com/airbnb/streamalert/pull/285
