### ISSUE TITLE
[conf] remove need to configure the prefix in multiple places

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#1086]
## Background

Currently, there is a command to configure the 'prefix', which replaces a preset value in a handful of places. This can be prone to issues if one of these is missed.

## Desired Change

Store the prefix in _only_ one [place](https://github.com/airbnb/streamalert/blob/7d198a3273781f66465420e90886a3ce53ec7559/conf/global.json#L5). Every other place that the prefix is used, like [here](https://github.com/airbnb/streamalert/blob/7d198a3273781f66465420e90886a3ce53ec7559/conf/global.json#L4), should be programmatically interpolated instead of being hard-coded. We should still support using a 'custom' (un-prefix, user-provided) value (like the kms key alias, for example) if the user desires.

**Comment by jack1902** [comment]
@ryandeivert can this issue be closed now?

**Comment by ryandeivert** [comment]
fixed with #1114
