### ISSUE TITLE
[feature] Ability to send one Alert then Merge

### ISSUE THREAD

**Issue by jack1902** [airbnb/streamalert#1104]
## Background

I discussed the below with @Ryxias on slack. Creating this issue to track the idea

### Description

I would like the ability to be able to configure a `rule` so that when it triggers an `Alert` it sends it immediately to the configured outputs, but then proceeds to merge the next set of `Alerts` according to the `merge_by_keys` and `merge_window_mins`. 

### Why?

Simply put, the reason why i would like this feature is to get the security team moving on an `Alert` straight away, without waiting for it to be merged before they get notified. Then get additional `Alerts` that are merged to reduce the noise caused by a `rule`.

## Desired Change

A `rule` such as:

```
@rule(
    logs=['cloudtrail:events', 'cloudwatch:events'],  # Rule applies to these 2 schemas
    merge_by_keys=['useragent'],  # Merge alerts with the same 'useragent' key-value pair
    merge_window_mins=5,  # Merge alerts every 5 minutes
    outputs=['pagerduty:csirt', 'slack:security']  # Send alerts to these 2 outputs
)
def cloudtrail_root_account_usage(record):
    """Page security team for any usage of AWS root account"""
    return (
        get_first_key(record, 'userIdentity', {}).get('type') == 'Root' and
        not get_first_key(record, 'invokedBy') and
        get_first_key(record, 'eventType') != 'AwsServiceEvent'
    )
```

Where to send a `Alert` immediately, but then `merge` according to the settings before sending out a merged `Alert`.

- Also it could be possible to set this as a default behaviour, but have the ability to disable this per `rule`.

**Comment by chunyong-lin** [comment]
Good proposal. To add little history here,  before alert_merger feature implemented, an alert would be generated immediately after the event matched to a rule.
* Old pipeline: events -> giant rules engine (includes classifier) -> alert processor -> outputs
* Current pipeline: event -> classifier -> rules engine -> alert merger -> alert processor -> outputs

So, we probably can just send the event/alert to alert processor if the matching rule doesn't contain merger keys, a.k.a skip alert merger.

**Comment by jack1902** [comment]
# Additional explanation

```python
@rule(
  logs=['your-schema'],
  merge_by_keys=['alpha', 'beta'],
  merge_window_mins=30,
  merge_send_first_alert=True # Send the first Alert Then merge
)
def merged_rule(record):
    return True


record_1 = {
    "alpha": "foo",
    "beta": "bar"
    "other_key": "This record is sent to outputs straight away"
}

record_2 = {
    "alpha": "foo",
    "beta": "bar"
    "other_key": "..."
}

record_3 = {
    "alpha": "foo",
    "beta": "bar"
    "other_key": "..."
}
"""
Records 2 and 3 match record 1 (merge_by_keys). Therefor they are merged and sent after 30 minutes of
record_1 being recieved. If a record comes in after this 30 minute window (merge_window_mins), it goes
through the same process
"""

record_4 = {
    "alpha": "different",
    "beta": "different",
    "other_key": "This record doesn't match the ones being merged so is sent straight away and other ones that match are merged"
}
```

**Comment by jack1902** [comment]
This logic seems like it could go here within the `if datetime` statement:
https://github.com/airbnb/streamalert/blob/616c8ff4ada443bb4e1e54f28264b30e22f4622a/streamalert/alert_merger/main.py#L123-L130

**Comment by jack1902** [comment]
This has proven really difficult due to how the records selected by the `alert_merger` comes from 

https://github.com/airbnb/streamalert/blob/616c8ff4ada443bb4e1e54f28264b30e22f4622a/streamalert/shared/alert_table.py#L89-L102

Since the `initial_record` will always be caught up in this, this causes the next invocation to have a different `initial_record` within a `merge_group`, which gets sent out as if its the first one but it isn't. When it comes to the final merge of all alerts, these records get selected and merged into one final alert, even though there were two "initial" alerts.
