### ISSUE TITLE
[feature] Utilise sphinx-argparse for the CLI documentation

### ISSUE THREAD

**Issue by jack1902** [airbnb/streamalert#1126]
## Background

Having added some `streamalert-cli` commands, the documentation on the command line via `-h` and ReadTheDocs varies and is laborious to maintain.

### Description

A fantastic tool, to reduce this headache is `sphinx-argparse`. In short, it adds the ability to take an `argparse` parser and create documentation from the `descriptions` and everything else in the parser. A live example is the best to describe this: https://rdk.readthedocs.io/en/latest/references.html.

To utilise `sphinx-argparse` there would be a **LARGE** re-write of the underlying `streamalert_cli` so that it is setup nicely and easier to add to in the future.

With the re-write, it would be possible to create a package for the `streamalert_cli` tool, potentially naming it `streamalert` with a prog name of `sa` installed via `-e streamalert_cli`

## Desired Change

The ability to use `sphinx-argparse` in the documentation. To break out `cli` relevant bits to their respective pages, whilst still having pages that describe everything else. Such as:

- what are outputs? For relevant CLI commands, see `sa output` (the cli output is `sphinx-argparse` documentation generated by the messages and sub-commands on `sa output`

- what is a rule? To test rules locally see `sa test rules`

**Comment by ryandeivert** [comment]
Hey @jack1902 - is this at all similar to #573?

**Comment by jack1902** [comment]
@ryandeivert it's slightly related. The method for creating docs that you mention pull the docstrings from a function but still don't assist in creating documentation for the `cli`. The example linked does this cli documentation very well as it is a direct map of what will be printed with commands such as `outputs -h`

The other thing I forgot to add was that currently there are errors in the cli when using commands like `./manage.py lookup-tables` `no subcommand stackstrace`
