### ISSUE TITLE
[RFC ] Backward compatibility discussion for Parquet format support

### ISSUE THREAD

**Issue by chunyong-lin** [airbnb/streamalert#1143]
## Background
We are currently working on merging parquet support to release-3-1-0 branch. The origin PR is #874 (based on v2) which has been reworked in #1115 and based on release-3-1-0 branch. The discussion here will  be focus on PR #1115. 

During the testing in staging environment, I realize that we should have backward compatibility to support both JSON and Parquet data format. Because an Athena table will only be able to load one type of data, either JSON and Parquet. Once we flip the switch to change the data to Parquet format, the existing data in JSON format will have to either move to another database/tables, or to  be converted to parquet format. I would like to dump my brain here and share with all contributors. Would love to hear your ideas as well.

#### Backward Compatibility
* A new setting `data_format` will be added to `conf/lambda.json` under `athena_partition_refresh_config`. Support format will be `json` and `parquet`, default to `null` in v3.1.0. StreamAlert will raise a mis-configuration error when user upgrade StreamAlert to v3.1.0 without explicitly set `store_format` to either `parquet` or `json`. 
* In the future release, it will set the default `store_format` to `parquet`. We want users to have graceful upgrade instead of break their historical search pipeline.
  Current configuration:
https://github.com/airbnb/streamalert/blob/2162c64f269afa47710b8adb4d922b2865e179be/conf/lambda.json#L53-L55
  So the new default configuration will look like
  ```
    "athena_partition_refresh_config": {
      "concurrency_limit": 10,
      "store_format": null,
      "log_level": "info"
    },
  ```
  
* Available values for `store_format` is `parquet` or `json`
  ```
    "athena_partition_refresh_config": {
      "concurrency_limit": 10,
      "store_format": "parquet",
      "log_level": "info"
    },
  ```
  Or
  ```
    "athena_partition_refresh_config": {
      "concurrency_limit": 10,
      "store_format": "json",
      "log_level": "info"
    },
  ```

#### Migrate existing JSON data
If the user choose and upgrade to Parquet format for historical searching, all Athena tables need to be recreated and set data format to `parquet`. It means the existing JSON data won't be searching from the new tables. We can provide proper approach to migrate existing JSON data.

* Option 1: Migrate to new location but still in JSON format
  It is possible to provide a script or integrate with StreamAlert cli to create tables in a new database and add partitions by enumerating S3 data buckets.
  * pros
    * Cost efficient: it will generate cost related to S3 List, Get and Athena create database, tables and Alter Tables API calls
    * Fast: It should be fast, because it will only enumerate S3 data bucket and add partitions to Athena tables in new database.
  * cons
    * Data is still in JSON format, so the historical searching against these data will be still slow
    * Increase maintenance burden because we will maintain another database.
* Option 2: Convert JSON format to Parquet
  Provide a one time script to convert all existing JSON data to parquet and integrate with new data in the same tables.
  * pros
    * We will have all historical data in consistent format, Parquet. 
    * All historical data will be searchable in godspeed.
    * It is possible to use `MSCK REPAIR TABLE` to load all new partitioned parquet data.
  * cons
    * It may cost lots of $$$$ to convert years of historical data if some one have StreamAlert historical searching feature enabled for years. We are not only List and Get objects from S3, but also Put objects to S3 and it is more expensive action. 
    * It will take longer time to finish the conversion.

**Comment by gavinelder** [comment]
Not saying this is best but as SA has no official Python3 release yet and the hope is users will do a fresh deploy so this should be considered as a less engineering time option.

- Option 3: Drop JSON Support & have users provision a new s3 location for  historic search.

  For users who wish to migrate existing data to parquet provide a one time script to convert selected  SON data to parquet and integrate with new data in the same tables.

  For users who wish to retain their existing Athena table in JSON no action outside of providing a new bucket is required (We could add a bucket & table suffix to make this automatic & non breaking) so users who do upgrade would just have a second DB table and bucket and then can choose at a later stage to migrate or retain
    - pros
       - removes needs to support JSON in the future
       - Users who wish to migrate historical data to benefit from fast search can opt to if they wish
       - Users would have two athena DB's one in JSON on in Parquet so they would retain historical search without spending $$$$
       - This allows users to migrate specific tables of interest vs all. 
    - cons 
       - This is a breaking change. 
       - This would result in an extra S3 bucket being provisioned for the new format. 
       - Historical Data would be split so SQL knowledge would be required for complex queries.

**Comment by chunyong-lin** [comment]
This is done in #1115
