### ISSUE TITLE
Migrate athena_partition_refresh lambda function to tf_lambda module

### ISSUE THREAD

**Issue by chunyong-lin** [airbnb/streamalert#1144]
related to: #1090

## Background
We will keep `athena_partition_refresh` lambda function forverrrrrrrr. So we need to migrate the function to use `tf_lambda` module to take advantage of code reuse and predefined alarms.

## Desired Change
Migrate the function to use [terraform/module/tf_lambda](https://github.com/airbnb/streamalert/tree/release-3-1-0/terraform/modules/tf_lambda)

**Comment by ryandeivert** [comment]
complete with #1217
