### ISSUE TITLE
[publishers] decouple alert publishers and tests

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#1149]
## Background

If the current [publishers](https://github.com/airbnb/streamalert/tree/release-3-0-0/publishers) are deleted/modified, they will break current [unit tests](https://github.com/airbnb/streamalert/tree/release-3-0-0/tests/unit/streamalert/alert_processor/publishers). This should not be the case, and we need to come up with away to either:

1) Have some "default" publishers that are *not* in the root `publishers` directory. These could be placed in `streamalert/shared/publishers` (?) or something similar, and unit tests could be relocated to `tests/unit/streamalert/shared/...` to align with this change.
2) Keep the `publishers` directory in the root, but *migrate* unit tests to _within_ that directory, (instead of in the root `tests/unit` directory). Proposed structure:

```
publishers/
├── community
│   ├── pagerduty
│   └── slack
└── tests
    └── unit
        └── publishers
            └── community
                ├── pagerduty
                └── slack
```

Then the unit test script should be updated to test this directory also.

Additionally, the [hard-coded](https://github.com/airbnb/streamalert/blob/90c42f619325abe4984a8de850b9cd2ba6aaf316/streamalert/shared/publisher.py#L120) publishers directory should be updated to take user-configurable paths for importing publishers, similar to how rules and matchers current work.

**Comment by Ryxias** [comment]
# Foreword

Taking a look at the publisher tests I wrote, I'm really beginning to question the usefulness of unit tests for those.

It seems like it would be preferable to have publisher **_integration tests_** instead. Like some mechanism for the return value of `compose_alert` would be. I also think it's (currently) really annoying to figure out how to set up LookupTables for integration tests.


# Proposal
No more unit tests for publishers. Unit tests become strictly used for **StreamAlert Framework Code**.

## Publisher Integration Tests
Enhance our ability to test Publishers. Add the following to the integration `.json` config:

```
"publisher_tests": [
  [
    "$.record.field", 
    "is",
    "aaaa"
  ],
  [
    "$.record.otherfield",
    "in",
    ["thing1", "thing2"]
  ],
  ...
],
```

It specifies an array of conditionals.

## LookupTables Mocks per-test
Allow setting up LookupTable mocks more easily. Add the following to the integration `.json` config:

```
"lookup_tables": {
  "table1": {
    "key1": "asdfalkd",
    "key2": "addssejpfiwjef",
  },
 ... 
}
```

**Comment by ryandeivert** [comment]
This was complete with 3.1.0
