### ISSUE TITLE
[bug] athena data bucket not found

### ISSUE THREAD

**Issue by jack1902** [airbnb/streamalert#1158]
### Description

Carrying out a fresh deploy errors out when looking for a bucket `PREFIX-streamalert-data` This bucket i believe has been renamed to `PREFIX-streamalerts`

### Steps to Reproduce

Currently debugging how this is getting created but here are some file references i think are causing this.

Looking at files which call this function:
https://github.com/airbnb/streamalert/blob/9718c28d2da86d09b5be487f875e339c37a8a1ea/streamalert/shared/config.py#L70

This function should respect the `enabled` boolean

## Desired Change

This error not to happen on a fresh deployment

**Comment by ryandeivert** [comment]
resolved with #1163
