### ISSUE TITLE
Feature: Support NDJSON

### ISSUE THREAD

**Issue by ghost** [airbnb/streamalert#122]
Details: http://ndjson.org/

Example: https://support.onelogin.com/hc/en-us/articles/215214143-Streaming-Real-Time-OneLogin-Event-Data-to-your-SIEM-Solution

**Comment by jacknagz** [comment]
@mime-frame do we want to support this as an input? or an output?

**Comment by mime-frame** [comment]
@jacknagz 

**input** - the idea is onelogin would stream data to streamalert
