### ISSUE TITLE
Bug: ERROR does not cause test to fail

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#148]
**What**

I was running tests locally and saw the following (partially redacted):

```
foo
	[Pass]	test (s3): foobar1
StreamAlert [ERROR]: Invalid data: <StreamPayload valid:False log_source:None entity:blah.us-east-1 type:None record:None>....."
	[Pass]	test (s3): foobar2
```

Luckily, my eye caught this, as the output of the testing script at the end was:

```
(106/106)	Tests Passed
StreamAlertCLI [INFO]: Completed
```

**Comment by mime-frame** [comment]
An easier repro case:
- Create a rule
- Don't import `re`
- Attempt to use `re` in the rule
- Notice exceptions thrown in stdout, but all tests are shown as passing

**Comment by ryandeivert** [comment]
The original request to fail tests if tests result in `invalid data` has been added in https://github.com/airbnb/streamalert/pull/235. The latter context to fail on errors in rules themselves has not been resolved at this time.

**Comment by ryandeivert** [comment]
That said, if there is an error in a rule (ie- using `re` without importing) and the integration test event is supposed to result in an alert, this will fail tests. The only time it won't fail tests is when the integration test should not result in an alert (would result in a negative test result anyway)..

TBH - we can try all we want to account for user error (ie - using a module before importing it) but that should be up to the user to 1) write good rules and 2) pylint their code
