### ISSUE TITLE
Improvement: LOGGER.error - include stacktrace

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#151]
**Problem**

There are a few instances where we catch exceptions and output them like so:

`LOGGER.error('%s: %s', rule.rule_function.__name__, e.message)`

The only problem is what is outputted is cryptic and does not include the stack trace.

**Example**

Here is a real world error that was observed:

`StreamAlert [ERROR]: example_rule: None`

It's clear that the rule `example_rule` is throwing an exception, but it's not clear why.

**Proposal**

Output the stack trace. This was confirmed locally to help dramatically.

Example modification done in `rules_engine.py`:

```
    @classmethod
    def process_rule(cls, record, rule):
        try:
            rule_result = rule.rule_function(record)
        except Exception as e:
            rule_result = False
            // MODIFICATION - THIS WAS ADDED
            traceback.print_exc()
            LOGGER.error('%s: %s', rule.rule_function.__name__, e.message)
        return rule_result
```

With this additional statement, we now see something like the following 

```
`Traceback (most recent call last):
  File "/Users/<snip>/streamalert/stream_alert/rule_processor/rules_engine.py", line 143, in process_rule
    rule_result = rule.rule_function(record)
  File "/Users/<snip>/streamalert/rules/intrusion_detection/<snip>/<snip>.py", line 27, in foo_bar_baz
    rec['type'] == 'foo.bar.baz' and
KeyError: 'type'
```

Which is actionable and easy to understand

**Comment by austinbyers** [comment]
Even better, [`logger.exception`](https://docs.python.org/2/library/logging.html#logging.Logger.exception) will automatically log the exception:

```python
import logging
try:
    1 / 0
except ZeroDivisionError:
    logging.exception('Unexpected divide by zero')
```

prints
```
ERROR:root:Unexpected divide by zero
Traceback (most recent call last):
  File "<ipython-input-2-e5eafbc52646>", line 2, in <module>
    1 / 0
ZeroDivisionError: division by zero
```

**Comment by mime-frame** [comment]
Resolved
