### ISSUE TITLE
Feature: Alert statistics via Cloudwatch

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#157]
Per suggestion by scott.piper:

> You want stats on your alerts.  How often did they fire? When? To whom?  You could probably fiddle with JIRA/PagerDuty to do this, but it'd be nice for something to automatically aggregate these into a report for you daily or weekly.

Goal:
- Use Cloudwatch metrics to capture this information

**Comment by jacknagz** [comment]
This will most likely be achieved via QuickSight instead of CloudWatch.  

Athena tables will already have the data, which can be loaded and analyzed with QuickSight.  If we used CloudWatch we would potentially be duplicating stats.

**Comment by mime-frame** [comment]
Closing as a result of #282
