### ISSUE TITLE
Enhancement: Custom Alert Body

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#172]
## Background

Incoming logs to StreamAlert can contain a multitude of fields and context around an event.  However when alerts are generated and triaged, sometimes there are unnecessary fields which clutter an alert.

## Desired Outcome

The ability to customize a record returned from a rule.  This could be removal (or additions) of fields, or anything else to make triage easier.

An example implementation I thought of could be something like:

```
@rule(logs=['test'], matchers=[], outputs=['pd'])
def test_rule(rec):
  result = 'test' in rec
  del rec['unnecessary-field']

  return result, rec
```

**Comment by Ryxias** [comment]
This has now been handled in AlertPublishers, released in `v2.2.0`
