### ISSUE TITLE
Improvement: Invoke alert processor directly from rule processor

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#189]
At the moment, we use AWS's SNS to publish alerts from the rule processor to an SNS topic. This in turn fires the alert processor lambda, sending the alert(s) to the alert processor in an SNS message payload.

We should migrate away from this to a model that uses boto3 to invoke the alert processor directly from the rule processor. See boto3 [docs](http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.invoke) for more info.

As an added bonus, this cleans up a lot of code and makes a lot of 'formatting' requirements we currently have non-existent. For instance, we don't have to construct an SNS payload, and can send JSON data however we want to.

**Comment by austinbyers** [comment]
👍  👍  👍
