### ISSUE TITLE
Terraform: Do Not Refresh State For Every Deploy Step

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#194]
## Background

During the deployment process, Terraform runs and refreshes state several times.  To shorten this process, the state refresh can be skipped after the first iteration with `-refresh=false`

**Comment by ibrahimsharaf** [comment]
Hi @jacknagz, I am interested in taking this one, where can I start?

**Comment by jacknagz** [comment]
hey @ibrahimsharaf, [this function](https://github.com/airbnb/streamalert/blob/master/stream_alert_cli/helpers.py#L101) essentially needs a new kwarg for `refresh_state`, where it would conditionally add `-refresh=false` to the Terraform command.  Hope that helps!

**Comment by austinbyers** [comment]
Closed via #604. This will be released with v2.0.0
