### ISSUE TITLE
Feature: Threat intelligence (IOCs)

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#2]
Target: Q3'17

StreamAlert will support comparing logs against traditional indicators of compromise (IOCs), which can range from thousands to millions in volume. This will be built in a way that's provider agnostic, allowing you to use ThreatStream, ThreatExchange, or whatever your heart desires.

**Comment by jacknagz** [comment]
Closing this per the 1.6 release notes: https://github.com/airbnb/streamalert/releases/tag/v1.6.0
