### ISSUE TITLE
Discussion: Integration Testing with Localstack

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#233]
Atlassian's [Localstack](https://github.com/localstack/localstack#integration-with-nosetests) is a framework for integration testing AWS services.  It would be interesting to see how this can be integrated with our current test suite to test inter-service communication.

**Comment by 0xdabbad00** [comment]
Another option just released today: https://aws.amazon.com/blogs/aws/new-aws-sam-local-beta-build-and-test-serverless-applications-locally/

**Comment by ryandeivert** [comment]
if we do this, it would be with something more like SAM than localstack, so closing out

**Comment by jacknagz** [comment]
Yeah, SAM/SAR is a great alternative and has local testing via Docker.
