### ISSUE TITLE
Use SSM/Parameter Store for storing output config secrets

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#240]
## Why
When adding a new output configuration via `stream_alert_cli.py`, secrets are currently encrypted with a KMS key and then stored in a `<prefix>.streamalert.secrets` bucket in S3. This involves a handful of operations and adds some unnecessary complexity. This would also make it easier to access/decrypt the secrets when sending to a given output. The encrypted blob from S3 would not have to be cached on disk and then decrypted with KMS - this could all happen in memory with the SSM get_parameter function.

## Requested Changes
Utilize [AWS's SSM via boto3](http://boto3.readthedocs.io/en/latest/reference/services/ssm.html) to store sensitive information.
The [`put_parameter`](http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.put_parameter) function can be used in conjunction with a KMS keyID to encrypt the sensitive integration key info being stored.
* This change should account for current secrets being stored in S3 and offer a way to migrate them to SSM.
* Support for deleting old output configurations via the cli should also be added.
  * Renaming of configurations should be considered as well.

**Comment by jack1902** [comment]
Will start work on this tomorrow evening :). from my understand of SA, the following locations utilise this secret_store:
- alert_processor (via outputs.get_creds)
- streamalert_cli (configuring outputs)

Are there any locations this s3 secret_store is accessed ? (i could hunt through the code base but tribal knowledge is a quick win)

**Comment by jack1902** [comment]
@ryandeivert I believe this can be closed?

**Comment by ryandeivert** [comment]
fixed with #1142
