### ISSUE TITLE
Improvement: Rename `log_patterns` to `required_key_values`

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#258]
**Proposal**

Rename `log_patterns` to `required_key_values`

Why:
- It more accurately captures what it does (it's not confusing)

**Work required**
- Code refactor
- Docs refactor

**Comment by ibrahimsharaf** [comment]
Hi @mime-frame, I'll start working on this one.

**Comment by jacknagz** [comment]
hey @ibrahimsharaf thanks for taking this on! unfortunately we no longer want to make this change (this is slightly outdated)
