### ISSUE TITLE
Improvement: Fail harder for StreamAlertOutput errors

### ISSUE THREAD

**Issue by ghost** [airbnb/streamalert#276]
**Overview**

When a rule has something defined in `outputs` that does not exist in `outputs.json`, it does output the following on stdout:

`StreamAlertOutput [ERROR]: The output 'pagerduty:example' does not exist!`

However:
- It is not in red font
- It is not output at the end (aka it hides amongst hundreds of lines of text)
- It does not cause `python stream_alert_cli.py lambda test --processor all` to fail; e.g. it can show everything as passing

I managed to catch this by accident when redirecting output like so:
- `python stream_alert_cli.py lambda test --processor all > foo.txt`

**Reproduction steps**

- Modify one of your rules' outputs - take off the last letter for example
- Re-run your tests, notice everything as passing and notice how you see nothing red

**Comment by ryandeivert** [comment]
the way the alert processor is now architected, this is no longer an issue
