### ISSUE TITLE
Support ingestion of logs via fetching/polling from RESTful APIs

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#278]
In its current state, StreamAlert is able to receive log data via a *push*-like approach, wherein other services (AWS SNS, Kinesis, S3) are able to *send* data into the Rule Processor lambda function for processing.

This proposal is to incorporate a flexible *poll*-like model into StreamAlert that would allow for scheduled fetching of logs via RESTful APIs that could then be handed off to the Rule Processor lambda function for processing.

The idea is that this would be extensible and offer the ability to support practically any generic SaaS application, RESTful endpoint, etc. A few bullet point use cases could include retrieving logs from services provides such as OneLogin, DUO Security, Google Admin, etc and batching/formatting them in a way that the Rule Processor could easily ingest & process.

**Comment by glaslos** [comment]
Shouldn't a scheduled event triggering lambda to fetch and prepare data be something that I create to feed data into "Stream"Alert? This proposal sounds a bit against the concept of serverless and add a data producer to something I considered a pure data consumer.

**Comment by jacknagz** [comment]
@ryandeivert:

> In its current state, StreamAlert is able to receive log data via a push-like approach, wherein other services (AWS SNS, Kinesis, S3) are able to send data into the Rule Processor lambda function for processing.

It's worth noting that Kinesis is actually a polling method.  Lambda checks the stream every 250ms and a static [batch of records](https://github.com/airbnb/streamalert/blob/master/terraform/modules/tf_stream_alert_kinesis_events/main.tf#L30) is analyzed.

@glaslos: 
> Shouldn't a scheduled event triggering lambda to fetch and prepare data be something that I create to feed data into "Stream"Alert? 

I believe @ryandeivert is suggesting the creation of a framework that would be generic enough for most use cases to avoid duplication of effort.  Users always have the option of creating their own producer by whichever preferred means.

> This proposal sounds a bit against the concept of serverless and add a data producer to something I considered a pure data consumer.

Scheduled jobs can run in Lambda just fine via [CloudWatch Scheduled Events](http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html), this is actually how you connect a Lambda function to a SQS Queue.
