### ISSUE TITLE
StreamAlertOutput [ERROR]: an error occurred during credentials decryption (Slack)

### ISSUE THREAD

**Issue by JJediny** [airbnb/streamalert#283]
`
StreamAlertOutput [ERROR]: an error occurred during credentials decryption: {'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 400, 'RequestId': 'e6a571c3-8da2-11e7-b06a-4573c2972fd5', 'HTTPHeaders': {'x-amzn-requestid': 'e6a571c3-8da2-11e7-b06a-4573c2972fd5', 'content-length': '39', 'server': 'Server', 'connection': 'keep-alive', 'date': 'Wed, 30 Aug 2017 16:47:25 GMT', 'content-type': 'application/x-amz-json-1.1'}}, 'Error': {'Message': '', 'Code': u'InvalidCiphertextException'}}
StreamAlertOutput [ERROR]: Failed to send alert to slack
`
### Steps to recreate
python manage.py lambda test --processor all :+1: 
python manage.py output new --service slack :+1: 
python manage.py lambda deploy --processor all :+1: 
python manage.py live-test --cluster prod :-1: 

This looks like a KMS error? is there a good way to debug output errors? Couldn't find any in the docs

**Comment by ryandeivert** [comment]
hey @JJediny thanks for submitting the issue! I'm going to take a look at this today and will reach out to you on the StreamAlert slack with questions

**Comment by JJediny** [comment]
To wrap this up - the issue was `python manage.py output new --service slack` was created to a different KMS store than was stored in tf.state so lookup/decrypt failed. This was caused by having to rename KMS twice - due to having to `terraform destroy` for unrelated reasons. AWS places a delete policy on KMS with a 30-day deletion protection, which doesn't allow for streamalert to reuse/re-create an already created KMS store (hence having to create an entirely new store). @ryandeivert good to close from me, really appreciate all the help from the team!

**Comment by ryandeivert** [comment]
Thanks for the update @JJediny! Closing out
