### ISSUE TITLE
Improvement: Visit 'admin' privileges

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#29]
Context:
- https://streamalert.readthedocs.io/account.html#administrator
- https://streamalert.slack.com/archives/general/p1486614692000033

**Comment by jacknagz** [comment]
- [ ] Update the docs with whitelisted AWS permissions
- [ ] Create a role which all SA CLI users can inherit from which gives them only the access they need as well as the ability to read Terraform statefiles

**Comment by mime-frame** [comment]
https://www.streamalert.io/account.html
