### ISSUE TITLE
Test cases for rules named incorrectly

### ISSUE THREAD

**Issue by 0xdabbad00** [airbnb/streamalert#290]
I love that you have tests for your rules!  However, I noticed the names of these tests, when they aren't supposed to fire, seem misleading to me.  For example, https://github.com/airbnb/streamalert/blob/0b1ad9f689b8d045eb1a079d5ec5c88c4a64c68a/tests/integration/rules/cloudtrail_critical_api_calls.json#L371 is labeled `CloudTrail - Critical API - False Positive Case`, but this is a True Negative, not a False Positive.  A False Positive would be a test that is not supposed to fire, but does.  In this case, you are testing to ensure that something that isn't supposed to fire, doesn't, which  should be called a True Negative.

**Comment by mime-frame** [comment]
Heya @0xdabbad00!

Good call out, we've switched to Ruby-style unit test descriptions and forgot to update a few. I'll have a PR up today.

**Comment by mime-frame** [comment]
@0xdabbad00 This has been addressed via https://github.com/airbnb/streamalert/pull/296.
