### ISSUE TITLE
Discussion: Test Framework for AWS Lambda functions

### ISSUE THREAD

**Issue by JJediny** [airbnb/streamalert#294]
**For discussion purpose only**

Is it worth considering a local lambda testing framework like OpenFaaS for docker? https://github.com/alexellis/faas 

I'm finding the constant test (works) -> upload (doesn't really work) workflow laborious

**Comment by mime-frame** [comment]
> I'm finding the constant test (works) -> upload (doesn't really work) workflow laborious

Can you clarify this a bit? We want to ensure we understand what's working well, what isn't and why you think OpenFaaS will help. Thanks @JJediny !

**Comment by JJediny** [comment]
Yea it's more about the parity of a local dev environment to AWS lamdba - to make sure the function is triggered as intended before having to upload a new .zip alerting bundle and re-versioning it as part of the testing process... I think Atlassian localstack may be better suited for this so best to move the convo to #233
