### ISSUE TITLE
Feature: Custom Alert text based on configuration and fields

### ISSUE THREAD

**Issue by 0xdabbad00** [airbnb/streamalert#305]
When alerts are written to Slack, they provide a title, a description of the alert (as extracted from the rule's source code comment), and the event that caused the alert.  I would like the ability to format the text of the alert.  For example, for the sample alerts, there is one for cloudtrail_critical_apis.  I would like to high-light in the alert text, who did it (.userIdentity.arn) and what they did (.eventName) to more easily understand what happened instead of expanding the json and looking through it for the information that most interests me.  Is this possible?

**Comment by mime-frame** [comment]
@0xdabbad00 Good q. While you might be interested in `.userIdentity.arn`, another StreamAlert user might be interested instead in having another field highlighted or bolded. Long story short, in order to meaningfully ship this, we'd have to create a feature that allows a user to configure on a per schema and field basis what they want highlighted, which isn't trivial.

I'll be honest and say we won't ship this in the short or midterm, but hope to look at it in the future.

**Comment by mime-frame** [comment]
@0xdabbad00 One way to address this, and generally improve one's ability to triage an alert, is to put triage steps in the description of the alert. These steps can highlight what fields should be looked at first and what one should be reasoning about.  We internally do this, that way an alert (or a case if alerts go into a downstream case management system) has all the context one needs to effectively triage it.

**Comment by 0xdabbad00** [comment]
My interest is to have templating for the text of the text of the alert.  For example, in ElastAlert, you can describe your alert's title as `"Issue {0} occurred at {1}"` and then define:
```
alert_subject_args:
- issue.name
- "@timestamp"
```
See http://elastalert.readthedocs.io/en/latest/ruletypes.html#alerts

You can also specify if you just want the title of the alert, to include the event text, or some other configurations.

My interest is to do something similar for StreamAlert.

**Comment by mime-frame** [comment]
@0xdabbad00 Ah, that makes it crystal clear, thanks.

**Comment by 0xdabbad00** [comment]
Another way in which this would be useful is to enhance the text of the alert with additional logic and information.  For example, if you set up Cloudtrail rules, and you have multiple accounts, you might find yourself having to manually lookup up the AWS account ID's mentioned in the json of the alert, but it would be nicer for the alerts to have text that is built from a lookup table to say "Account: PROD (111111111111)" or "Account: Test (222222222222)" instead of just "Account: 111111111111" buried in the json.  Again, ElastAlert has such a concept with it's "Enhancements" (http://elastalert.readthedocs.io/en/latest/recipes/adding_enhancements.html).

**Comment by mime-frame** [comment]
Noted. We plan on shipping a feature called Enrichment that will provide simple or complex lookup abilities that can "decorate" a log or alert. Think DHCP lookups or the example you provided. That's going to happen in Q4 or Q1

**Comment by ryandeivert** [comment]
closing since I believe this is accomplished via https://github.com/airbnb/streamalert/pull/900
