### ISSUE TITLE
Allow for "unknown" account ID In VPC Flow Logs

### ISSUE THREAD

**Issue by 0xdabbad00** [airbnb/streamalert#315]
VPC Flow Log events normally include the account ID, for example:
```
2 123456789010 eni-abc123de 172.31.16.139 172.31.16.21 20641 22 6 20 4249 1418530010 1418530070 ACCEPT OK
```

However, for interfaces associated with some services this is specified as `unknown` resulting in an event like:
```
2 unknown eni-abc123de 172.31.16.139 172.31.16.21 20641 22 6 20 4249 1418530010 1418530070 ACCEPT OK
```

If you run `aws describe-network-interfaces` and look at `.NetworkInterfaces[].Attachment.InstanceOwnerId` you'll see your account ID for some interfaces, but also things like `amazon-elb`, `amazon-rds`, and `amazon-aws`.  NLB (and supposedly EFS) use the `amazon-aws` and for these, you'll end up with `unknown` for the account id in the VPC Flow Log event.

Due to this issue you'll get Lambda Invocation errors with StreamAlert, and therefore the schema for `cloudwatch:flow_logs` needs to be changed to allow for strings, or at least the string `unknown` at https://github.com/airbnb/streamalert/blob/99dc4634c8d470ca4b4f88713903b19a7b70be09/conf/logs.json#L765

**Comment by mime-frame** [comment]
Fixed! Note: if you have any rules doing integer comparisons on account ID that'll have to change with this schema update

**Comment by eugenesheyko** [comment]
Could you please advise where I can change the account to "string" in AWS Console?

**Comment by ryandeivert** [comment]
hi @eugenesheyko - if you're referring to setting an account alias, see [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html). however, this does not change the account ID value seen across all logs. Besides this suggestion, I don't think this is something we're able to provide any further guidance on, I'm sorry.
