### ISSUE TITLE
Alert Batching

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#321]
### Current Behavior

Each generated alert is sent individually to the Alert Processor from the Rule Processor.  With high throughput alerts, this can take 10-30 seconds in total.  

### Desired Results

Batch the alerts by alert type, or by the number of alerts to reduce the number of Alert Processor invocations.  This has many benefits, including cost savings and performance.

**Comment by austinbyers** [comment]
As of #612 (in the v2 release branch) , alerts are sent to a Dynamo table in batched write operations
