### ISSUE TITLE
Improvement: Publish the python library separate to the Reference Implementation

### ISSUE THREAD

**Issue by patrobinson** [airbnb/streamalert#33]
So I tried to implement StreamAlert today. As someone with pretty good experience in AWS I felt like the "tools" used to make things easy hindered me rather than helped me. The python library is ideally all I need, I can build the rest and do it using the tools I prefer to use instead of trying to understand how the existing implementation is built.

Ideally the `RuleHelper`, `RuleEngine` and `Classifier` are all that are required for the simplest python library. The rest (including the `Sink` function) are more a Reference Implementation than a part of the core library, there are various ways to implement them depending on your requirements.

My strong but weakly held opinion is that this repository blurs the lines between the StreamAlert core rules engine and the infrastructure implementation; they are too tightly coupled. For example:

- The same configuration that feeds the Classifier is used to generate the Terraform manifest.
- The sink function is part of the same code base as the function that generates the alert.
- There's a function that packages and deploys Lambda functions, when many tools already exist that do this ([Apex](https://github.com/apex/apex) and [Serverless](https://serverless.com/))

Don't get me wrong, I 😍 that you've provided the automation example of how to implement this and I wish more OSS projects would do it too.

**Comment by jacknagz** [comment]
Hey @patrobinson, this is a great suggestion.  I have also been thinking about moving the core library into a `pip` package.   If I'm understanding your use case, you just want the ability to feed the rules engine events and have it return a list of alerts without handling the actual delivery?

**Comment by jacknagz** [comment]
> The same configuration that feeds the Classifier is used to generate the Terraform manifest.

This is not accurate, there are config files used via the Lambda function (everything in `conf/`) and the `variables.json` used by the `stream_alert_cli`.

> The sink function is part of the same code base as the function that generates the alert.

This is tightly coupled currently because we provide the ability for end-to-end deployments (processing and alerting)

**Comment by patrobinson** [comment]
I'm still not clear how the API of the library would work, but ideally the Sink functionality should be left at as an exercise for the user to implement. But leaving the Sink function in the core library to be called if a flag is set wouldn't be a bad way to do it either.

**Comment by patrobinson** [comment]
After discussions in Slack, and reading into how Sink works, I think `Sink` should stay but be modified so you can provide your own SNS Topic as an argument to notify. The functionality we require can be achieved using the Fanout architecture of subscribing SQS queues to the Topic.

**Comment by jacknagz** [comment]
@patrobinson we can definitely make that work!

**Comment by jacknagz** [comment]
Hey @patrobinson, we recently implemented the ability to return a list of alerts from rule processing instead of handling it with SNS.  We have plans to work towards making the code a standalone Python package
