### ISSUE TITLE
Bug: Normalized field is not found in a nested structure

### ISSUE THREAD

**Issue by javuto** [airbnb/streamalert#333]
## Current Behavior

Writing a new rule that uses the data normalization capabilities, and in particular the `command` datatype. For carbonblack logs, the fields that are used (as defined in `types.json`) are in the same depth but for osquery logs those fields are usually within a nested structure and current tests do not match logs that should alert based on data normalization. For example, here is a carbonblack log:
```
{
    "data": {
    "cb_server": "cbserver",
    "command_line": "malicious_command",
    ...
}
```
System works as expected and `malicious_command` will be detected using `datatypes=['command']` in the rule. On the other hand here is a osquery sample log:
```
{
    "data": {
    "hostIdentifier": "osquery-host",
    "columns": {
        "command": "malicious_command",
        ...
    }
    ...
}    
```
Because the `command` field is nested within `columns`, the data does not seem to be matched properly.

## Desired Results

Data within nested structures will be extracted and used to match current and new rules. Both examples of logs should match a rule looking for `malicious_command` and at the moment only carbonblack logs do it.

**Comment by chunyong-lin** [comment]
Hi @javuto Unit [test case](https://github.com/airbnb/streamalert/blob/master/tests/unit/stream_alert_rule_processor/test_rules_engine.py#L606-L677) should cover this case.
