### ISSUE TITLE
Bug: Normalized Types is not reset during rule processing

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#351]
### Issue
The processing of rules will iterate over records within a payload, and then iterate over each rule attempting to process the rule against the record.

During this processing, we check to see if a rule utilizes the `datatypes` directive and then we do some logic to determine if this record has any keys that reflect these normalized `datatypes`. Any `normalized_types` that are discovered get cached on the `record` itself within the `normalized_types` key, seen [here](https://github.com/airbnb/streamalert/blob/master/stream_alert/rule_processor/rules_engine.py#L387).

However, this `normalized_types` key is never reset, and will remain populated with any normalized data values from previous rules. Future rules that are processed for this record will have previous datatypes populated, which can cause problems/result in misleading record data.

**Comment by chunyong-lin** [comment]
This issue has been fixed in PR #367.
