### ISSUE TITLE
Improvement: Rules Testing

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#36]
Background: https://www.streamalert.io/rules.html#rules-testing

Goals

- Each rule has it's own .py for testing vs one big `trigger_events.json` and `non_trigger_events.json`
- Those .py's support whitespacing (ex: JSON log over multiple lines) vs. requiring one event per line

**Comment by jacknagz** [comment]
Desired new format:

* Each rule test is contained in its own file under `test/integration/rules`
* Each rule test file contains one JSON object with the following format:

```
{
  "rule_name": "rule1",
  "records": [
    {
      "data": "string or map",            # the data to be read into the Lambda function
      "trigger": true/false                   # whether or not this data should trigger an alert
    },
    ...
  ]
}
```

After running the integration testing script, it will generate a coverage report:

```
rule name              num records           coverage
rule_1                 3                     0-100%
``` 

Additional support:

* The ability to fake field times (when searching in windows like last_hour)

**Comment by jacknagz** [comment]
Update #42 with this change

**Comment by jacknagz** [comment]
- [ ] Implement new testing suite for integration testing (described above)
- [ ] Move rule helpers into their own package folder
