### ISSUE TITLE
Use `LATEST` when reading from kinesis streams

### ISSUE THREAD

**Issue by 0xdabbad00** [airbnb/streamalert#364]
## Background

The event source mapping for the lambda that reads from the Kinesis Stream is set to `TRIM_HORIZON` instead of `LATEST`.  The result of this is that instead of the newest logs being looked at, the old logs are looked at.  So instead of logs being looked at as they arrive, they are looked at just as they hit the retention window of 24 hours.  This means that alerts are always delayed 24 hours instead of being immediate.

## Desired Change

Use `LATEST` instead of `TRIM_HORIZON` at https://github.com/airbnb/streamalert/blob/abbf80fafe68bb54eceeb1ef73bd130b955040ba/terraform/modules/tf_stream_alert_kinesis_events/main.tf#L33

**Comment by mime-frame** [comment]
Are you sure they're always delayed by 24 hours? As I read the documentation, it says it's FIFO vs. LIFO?

> TRIM_HORIZON - Start reading at the last untrimmed record in the shard in the system, which is the oldest data record in the shard.

This makes sense to me - why give preference to new records when you have old records that still haven't been processed? Esp. since records need to be analyzed within a given timeframe

Paging @jacknagz, @ryandeivert to confirm

**Comment by 0xdabbad00** [comment]
I just noticed my `GetRecords.IteratorAgeMilliseconds` is way too high, so looks like I diagnosed the problem incorrectly. I'm sorry.  I'm sheepishly closing this issue.

**Comment by jacknagz** [comment]
@0xdabbad00 feel free to reach out in Slack, we can help you troubleshoot and fix that

**Comment by Amay22** [comment]
@0xdabbad00 I am also using TRIM_HORIZON and even my `GetRecords.IteratorAgeMilliseconds` is too high. It kind of gets levelled out after a certain point and I have increased parallelism using more vCores and done almost everything I can to make it all work. Yet I am not able to get `GetRecords.IteratorAgeMilliseconds` down to an acceptable value.
