### ISSUE TITLE
Bug: Validation of datatypes is too strict 

### ISSUE THREAD

**Issue by chunyong-lin** [airbnb/streamalert#365]
## Background

In current implementation it requires all types in the rule parameter `datatypes` to be defined in `conf/types.json`.
For example, following rule will return `false` even normalized type `command` is defined. It is because the `fetch_values_by_datatype` helper will return an empty list due to code to validate datatypes at [here](https://github.com/airbnb/streamalert/blob/master/stream_alert/rule_processor/rules_engine.py#L282-L284) .
```
"""This is sample rule to alert on any suspicious use of wget"""
import fnmatch
from helpers.base import fetch_values_by_datatype

@rule(datatypes=['command', 'not_exist_normalized_type'])
def alert_suspecious_wget(rec):
    results = fetch_values_by_datatype(rec, 'command')
    for result in results:
        if fnmatch(result, "wget *"):
            return true
    return false
```

## Desired Change

Return value of normalized types if defined, and ignore normalized types which are not defined in `conf/types.json`.

**Comment by mime-frame** [comment]
If a rule has a type defined in `datatypes` that does not exist, we should throw an ERROR, not ignore it

**Comment by chunyong-lin** [comment]
Ideally, when we enable Threat Intel, we want to be alerted on if any of `datatypes` matching to IOC within one rule. In current implementation, we are not able to write one rule to alert on any datatypes matching to IOCs. 
For example, following rule will alert on logs from carbonblack, but it will not be able to alert on logs from cloudtrail. In [conf/types.json](https://github.com/airbnb/streamalert/blob/master/conf/types.json), `destinationDomain`, `fileHash` and `sourceAddress` are defined in carbonblack, but only `sourceAddress` defined in cloudtrail, cloudtrail logs will not have `fileHash`. 
```
# simplified rule
@rule(datatypes=['destinationDomain', 'fileHash', 'sourceAddress'])
def sample_rule(rec):
    # sample code here
```

Does it make sense?

**Comment by mime-frame** [comment]
What you're implicitly stating is that `datatypes` is an `AND` vs `OR` operation, which I believe we failed to discuss/reason about in the design phase.

If we look at the other "keys" within a rule definition, here's their current functionality:
- `logs`: OR
- `matchers`: AND
- `req_subkeys`: AND

I propose we

1) Keep `datatypes` as an `AND` operation
2) If an incoming record does not have all the required `datatypes`, the record does not get evaluated by the rule and an error is *not* thrown

In the example you illustrated, a CarbonBlack record would be evaluated by the rule, whereas a Cloudtrail record will not.

As you hint at, this works OK but you're slightly concerned about having to write a lot of rules to provide coverage for all CEF fields and having them applied against threat intelligence.

Auditing our existing conf/types.json file, we have 25 CEF fields:

```
    "command"
    "destinationAccount"
    "destinationAddress"
    "destinationDomain"
    "destinationPort"
    "deviceAddress"
    "eventName"
    "eventType"
    "fileHash"
    "fileName"
    "filePath"
    "fileSize"
    "message"
    "processName"
    "processPath"
    "receiptTime"
    "region"
    "severity"
    "sourceAccount"
    "sourceAddress"
    "sourcePort"
    "sourceUserId"
    "transportProtocol"
    "userAgent"
    "userName"
```

I don't see this number growing over time. I also see each field requiring it's own "ignorelist" to address false positives as they crop up. Trying to squeeze all of the FP's into a single rule and it's ignorelist seems like a mess. Additionally, having a rule for each type allows users (and us) to slowly onboard a CEF type. 

As a result, I'm personally comfortable with us having 25 rules, one for each CEF type, that's responsible for comparing that type against threat intelligence. As FP's pop up, users can address them in the appropriate rule and update tests as they see fit.

What do you think?

**Comment by chunyong-lin** [comment]
From resolving false positives point of view, I agree with your proposals. 
>  If I understand correctly, (1) and (2) are conditions that are already satisfied?

Yes, you are correct. 

I will update this use case to related design documentation. Also, I will close this issue.

**Comment by mime-frame** [comment]
After a use-case Javier raised, and giving it more thought, it should be an `OR` vs. `AND` operation. @chunyong-lin - can you make the appropriate changes?

**Comment by chunyong-lin** [comment]
Yes, I have the fix already, will send PR soon.
