### ISSUE TITLE
Terraform: design and implemantation

### ISSUE THREAD

**Issue by mazzy89** [airbnb/streamalert#406]
The project defines under the `terraform` folder tf resources. Under the CLI is then possible to find Python scripts to create Terraform resources in JSON format. I'm missing why this design. Can you explain me?

**Comment by ryandeivert** [comment]
Hi @mazzy89 and thanks for the question - can you reach out to us on the [StreamAlert slack](https://streamalert.herokuapp.com/) so we can better address your question?

**Comment by ryandeivert** [comment]
Handling inquiry via slack
