### ISSUE TITLE
Normalized Type Missing streamalert Prefix

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#413]
## Background

For fields added to the parsed record during rule processing, such as `envelope_keys` and `normalized_types`, they should always be prefixed with `streamalert:` to avoid collision with valid data fields.  `normalized_types` does not follow this convention.

## Desired Change

Add a constant for the `streamalert:normalized_types` field, similar to how `streamalert:envelope_keys` works.

https://github.com/airbnb/streamalert/blob/master/stream_alert/rule_processor/rules_engine.py#L372

**Comment by mime-frame** [comment]
@jacknagz Do we need to do anything to ensure the colon doesn't appear in the column name in Athena (and hence brick it)?

**Comment by jacknagz** [comment]
@mime-frame nope, the rule processor strips all special characters and replaces them with `_` prior to sending to Firehose
