### ISSUE TITLE
Improvement: persist lambda function metadata to S3

### ISSUE THREAD

**Issue by patrickod** [airbnb/streamalert#419]
## Current behavior

Currently the process of deploying either the rule processor or alert lambda functions causes the local working tree to become dirty as we record some metatada about the deployed functions (version, hash, object_key in S3). This makes it somewhat awkward to integrate streamalert into a CI pipeline as these changes then have to be committed back to the repository if the next user is to have an up to date view of the world.

## Desired Change

Were this metadata instead persisted to S3 it would be possible for users to regenerate the correct context at each new deployment. This in turn would make streamalert more amenable to CI pipelines as there would be no need to commit changes back into the source repository.

**Comment by ryandeivert** [comment]
Hi @patrickod and thanks for filing the issue! I wanted to quickly get your opinion on an alternative to S3 for this. We've been investigating using [AWS Parameter Store](http://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) more heavily for config related values. What are your thoughts on using it for this as well?

**Comment by patrickod** [comment]
+1 for ParameterStore. I've used it for configuration variable storage in applications before and found it to be great and very reliable. It's likely a better fit than S3 for this particular use case.

**Comment by jacknagz** [comment]
Changes have been merged to Terraform to better manage the deployment process (thanks you @austinbyers) to avoid a dirty repo state!

Closing this out.
