### ISSUE TITLE
[bug] Do not allow '_' (underscores) in prefix

### ISSUE THREAD

**Issue by securityclippy** [airbnb/streamalert#424]
## Background

If prefix contains an underscore, terraform will attempt to create and S3 bucket with an underscore when it builds the infrastructure.  This will result in an invalid bucket name error due to bucket name restrictions.

## Desired Change

upon prefix creation, validate allowed characters for bucket names.

## Logs

```aws_cloudtrail.streamalert: InvalidS3BucketNameException: Bucket name should not contain '_'```

**Comment by securityclippy** [comment]
Happy to submit a PR for this.  Could someone please assign to me?

**Comment by ryandeivert** [comment]
@securityclippy done!
