### ISSUE TITLE
modify configure prefix to configure sources with prefix as well

### ISSUE THREAD

**Issue by securityclippy** [airbnb/streamalert#432]
## Background

currently conf/sources.json contains an example prefix.  Because of the way its described, silly people (like me) may make the assumption that the prefix will be replaced when a prefix is configured. (it is not)

## Desired Change

enhance the configure prefix command to also change the prefixes in sources.json

**Comment by jacknagz** [comment]
Maybe something like this would be cool:

```
$ python manage.py configure sources --entity kinesis --name prod_stream_alert_kinesis --logs osquery,cloudwatch,ghe
```

**Comment by ryandeivert** [comment]
this doesn't really make sense, since "sources" and their log definitions can be arbitrary and we shouldn't do what we "expect". the onus has to be on the user for this. the comment from jack would be a nice feature, but a completely different feature than the request.
