### ISSUE TITLE
Improvement: Use -auto-approve=false instead of custom request logic

### ISSUE THREAD

**Issue by austinbyers** [airbnb/streamalert#438]
## Background

The StreamAlert CLI was built before Terraform had the `-auto-approve` flag. Before applying changes, StreamAlert runs `terraform plan` and asks for user confirmation before `terraform apply`.

With `-auto-approve=false`, Terraform itself will do this exact behavior. It's faster (because it already generated the plan) and will simplify some of the CLI code.

## Desired Change

- Use `-auto-approve=false` for all Terraform applys
- Remove custom "Would you like to continue" logic from CLI

**Comment by ryandeivert** [comment]
resolved with: https://github.com/airbnb/streamalert/pull/604
