### ISSUE TITLE
Add "requirements_top_level.txt"

### ISSUE THREAD

**Issue by austinbyers** [airbnb/streamalert#439]
## Background

The `requirements.txt` file now lists 79 dependencies, many of which are out of date (for example, boto3). This has two downsides:

- Upgrading the requirements list is not trivial because an upgrade may add or remove dependencies as well.
- It's hard to see, at a glance, what high-level packages are actually used (boto3, sphinx, etc)

## Desired Change

Add a separate `requirements_top_level.txt` which stores only the top-level dependencies. Then, updating `requirements.txt` is much easier:

```bash
pip install -r requirements_top_level.txt --upgrade
pip freeze > requirements.txt
```

BinaryAlert uses this model to great success, and it was inspired by [this blog post](http://www.jfabre.com/how-not-to-to-pip-requirements).

**Comment by ryandeivert** [comment]
Can't we just the same benefit by just having `requirements.txt` be the top level reqs by default? tbh i think it's safer/better to let the top level package handle all of it's dependencies and we don't manage that at all

**Comment by austinbyers** [comment]
You could, but as the blog points out it's considered best practice to freeze all of your requirements exactly. This ensures the same environment across CI, dev, etc. Top-level packages may support a range of underlying packages (e.g. `boto3` might support `botocore ~> 1.0.0`, of which there could be several options)

**Comment by stoggi** [comment]
I use pipenv (https://github.com/kennethreitz/pipenv) for this purpose. It combines `pip` and `virtualenv` to support features like freezing all packages in your virtual environment.

It can import from a requirements.txt file when you first run `pipenv --two install` in your StreamAlert repository. It generates two files: `Pipfile` (similar to `requirements_top_level.txt` in your example) and `Pipfile.lock` that it uses to freeze all packages in the virtual environment.

You can then start a new shell with the activated virtualenv with `pipenv shell` or run a single command:

    pipenv run -- python manage.py terraform build

**Comment by ryandeivert** [comment]
Suggestion: use `pipreqs` to determine actual dependencies (`pip install pipreqs && pipreqs --savepath requirements_top.txt`)

**Comment by jacknagz** [comment]
I think the proposed change is reasonable and provides consistency across our open source projects.
