### ISSUE TITLE
AWS console sign-in CloudTrail events do not contain requestID

### ISSUE THREAD

**Issue by stoggi** [airbnb/streamalert#447]
## Background

CloudTrail events for AWS console sign-ins do not contain the top level key `requestID`.

http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-aws-console-sign-in-events.html

In particular I would like to parse `SwitchRole` events via the `cloudtrail:events` schema from an s3 bucket.

Here is an example event:

```
{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "...",
        "arn": "...",
        "accountId": "...",
        "userName": "..."
    },
    "eventTime": "...",
    "eventSource": "signin.amazonaws.com",
    "eventName": "SwitchRole",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "...",
    "userAgent": "...",
    "requestParameters": null,
    "responseElements": {
        "SwitchRole": "Success"
    },
    "additionalEventData": {
        "RedirectTo": "...",
        "SwitchTo": "arn:aws:iam::12345:role/role-to-alert-on"
    },
    "eventID": "...",
    "eventType": "AwsConsoleSignIn",
    "recipientAccountId": "12345"
}
```

Note the absence of the `requestID` key. Why do you do this to me amazon?

## Desired Change

An easy solution would be to add `requestID` to the `optional_top_level_keys` array in the `cloudtrail:events` schema.

It looks like Service Events might also exclude the `requestID` (http://docs.aws.amazon.com/awscloudtrail/latest/userguide/non-api-aws-service-events.html).

Would adding `requestID` to the `optional_top_level_keys` break any existing rules?

**Comment by ryandeivert** [comment]
@stoggi adding the `requestID` as an optional top level key, as you suggest, should not break anything and is what I would recommend for this

**Comment by stoggi** [comment]
@ryandeivert ok, cheers. I can submit a PR.

Would you also be interested in a community cloudtrail rule to alert on SwitchRole (and AssumeRole) to test the schema?
