### ISSUE TITLE
Improvement: Package dependencies for lambda

### ISSUE THREAD

**Issue by strcrzy** [airbnb/streamalert#46]
We already have [code](https://github.com/airbnb/streamalert/blob/e29fe937318df5d83400dde65a485dcf0ad78037/stream_alert_cli/package.py#L160) to package and deploy third party libraries, but it might be cool to have SA package its own dependencies (from `requirements.txt`) into the deployment archive as well. #40 introduced a new lambda dependency, and other revisions likely will too.

We *could* track these in `third_party_libs` in `variables.json` but IMO those should just be the dependencies of the rules themselves rather than their underlying infrastructure.

**Comment by ryandeivert** [comment]
this is actually complete and we have these in the packaging logic
