### ISSUE TITLE
Setting `firehose` output causes errors in tests

### ISSUE THREAD

**Issue by 0xdabbad00** [airbnb/streamalert#460]
## Background

In `global.json` under `"infrastructure": {` at 
https://github.com/airbnb/streamalert/blob/73d2c9aed65e3d3d24a3389a70f73f9c59fbad23/conf/global.json#L9
add 
```
"firehose": {
      "enabled": true,
      "s3_bucket_suffix": "streamalert.data",
      "buffer_size": 64,
      "buffer_interval": 300,
      "compression_format": "GZIP"
    }
```
as described on https://streamalert.readthedocs.io/firehose.html

Then run `./tests/scripts/rule_test.sh` this results in the following error repeated:
```
backoff [ERROR]: Backing off firehose_request_wrapper(...) for 0.9s (ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the PutRecordBatch operation: Stream streamalert_data_systemlogs under account 123456789012 not found.)
StreamAlertShared [INFO]: [Backoff]: Trying again in 0.907155 seconds after 1 tries calling firehose_request_wrapper
```

## Desired Change

Allow the tests to run.  I'm still trying to figure out how to resolve this.

**Comment by jacknagz** [comment]
@0xdabbad00 are you on latest?

**Comment by 0xdabbad00** [comment]
Looks like this is not an issue with the latest code.  I'll sync our local repo with upstream and hopefully that resolves it.  We had just sync'd last week.

**Comment by 0xdabbad00** [comment]
I updated to latest and still ran into the issue.  Eventually, I figured out the issue seems to be due to us not running `us-east-1`.  Change the `region` in `conf/global.json` to `us-west-2`, and you'll run into the same issue on the latest code.  This indicates there seems to be a dependency in the test code on `us-east-1`.

**Comment by 0xdabbad00** [comment]
I set `region_name` to `us-west-2` here and the tests run fine now: https://github.com/airbnb/streamalert/blob/f6b5f6e4296090ded404c55fa9a64d2e5eaacce9/stream_alert/rule_processor/handler.py#L122

so I'm trying to figure out where that gets set.

**Comment by 0xdabbad00** [comment]
I changed the code at https://github.com/airbnb/streamalert/blob/82b6119c6a8b2fa3a9e62f576fd833a182f0e814/stream_alert_cli/helpers.py#L478 to:

```
if not cluster:
        region = config['global']['account']['region']
        context.invoked_function_arn = (
            'arn:aws:lambda:{}:123456789012:'
            'function:test_streamalert_processor:development').format(region)
```

Now the tests work.  Want me to send a PR for that short change? I don't know what all else this impacts.

**Comment by jacknagz** [comment]
@0xdabbad00 sounds good
