### ISSUE TITLE
BucketRegionError: incorrect region, the bucket is not in 'ap-southeast-1' region

### ISSUE THREAD

**Issue by scrapbird** [airbnb/streamalert#469]
## Background

When attempting to run `python manage.py terraform init` and specifying the ap-southeast-2 region I get the following error:

> StreamAlertCLI [INFO]: Issues? Report here: https://github.com/airbnb/streamalert/issues
> 
> Are you sure you want to destroy? (yes or no): yes
> Downloading modules...
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> 
> Terraform has been successfully initialized!
> 
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> 
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
> StreamAlertCLI [INFO]: Planning infrastructure
> provider.aws.region
>   The region where AWS operations will take place. Examples
>   are us-east-1, us-west-2, etc.
> 
>   Default: us-east-1
>   Enter a value: ap-southeast-1
> 
> Refreshing Terraform state in-memory prior to plan...
> The refreshed state will be used to calculate this plan, but will not be
> persisted to local or remote state storage.
> 
> aws_s3_bucket.streamalerts: Refreshing state... (ID: [REDACTED].streamalerts)
> aws_s3_bucket.logging_bucket: Refreshing state... (ID: [REDACTED].streamalert.s3-logging)
> aws_s3_bucket.terraform_remote_state: Refreshing state... (ID: [REDACTED].streamalert.terraform.state)
> aws_s3_bucket.stream_alert_secrets: Refreshing state... (ID: [REDACTED].streamalert.secrets)
> aws_kms_key.stream_alert_secrets: Refreshing state... (ID: 7c7fe52f-531c-410f-bb8e-0702c4e5b9d1)
> aws_s3_bucket.lambda_source: Refreshing state... (ID: [REDACTED].streamalert.source)
> aws_kms_alias.stream_alert_secrets: Refreshing state... (ID: alias/stream_alert_secrets)
> data.aws_iam_policy_document.alert_processor_cloudwatch: Refreshing state...
> data.aws_iam_policy_document.lambda_assume_role_policy: Refreshing state...
> data.aws_iam_policy_document.rule_processor_invoke_alert_proc: Refreshing state...
> data.aws_iam_policy_document.streamalert_rule_processor_firehose: Refreshing state...
> data.aws_iam_policy_document.alert_processor_s3: Refreshing state...
> data.aws_iam_policy_document.streamalert_cloudwatch_role_assume_role_policy: Refreshing state...
> data.aws_iam_policy_document.cloudtrail_bucket: Refreshing state...
> Error refreshing state: 5 error(s) occurred:
> 
> * aws_s3_bucket.terraform_remote_state: 1 error(s) occurred:
> 
> * aws_s3_bucket.terraform_remote_state: aws_s3_bucket.terraform_remote_state: error reading S3 bucket "[REDACTED].streamalert.terraform.state": BucketRegionError: incorrect region, the bucket is not in 'ap-southeast-1' region
> 	status code: 301, request id: , host id:
> * aws_s3_bucket.stream_alert_secrets: 1 error(s) occurred:
> 
> * aws_s3_bucket.stream_alert_secrets: aws_s3_bucket.stream_alert_secrets: error reading S3 bucket "[REDACTED].streamalert.secrets": BucketRegionError: incorrect region, the bucket is not in 'ap-southeast-1' region
> 	status code: 301, request id: , host id:
> * aws_s3_bucket.lambda_source: 1 error(s) occurred:
> 
> * aws_s3_bucket.lambda_source: aws_s3_bucket.lambda_source: error reading S3 bucket "[REDACTED].streamalert.source": BucketRegionError: incorrect region, the bucket is not in 'ap-southeast-1' region
> 	status code: 301, request id: , host id:
> * aws_s3_bucket.logging_bucket: 1 error(s) occurred:
> 
> * aws_s3_bucket.logging_bucket: aws_s3_bucket.logging_bucket: error reading S3 bucket "[REDACTED].streamalert.s3-logging": BucketRegionError: incorrect region, the bucket is not in 'ap-southeast-1' region
> 	status code: 301, request id: , host id:
> * aws_s3_bucket.streamalerts: 1 error(s) occurred:
> 
> * aws_s3_bucket.streamalerts: aws_s3_bucket.streamalerts: error reading S3 bucket "[REDACTED].streamalerts": BucketRegionError: incorrect region, the bucket is not in 'ap-southeast-1' region
> 	status code: 301, request id: , host id:
> StreamAlertCLI [ERROR]: An error occurred while running: terraform plan -var-file=../conf/lambda.json -destroy
> ['terraform', 'plan', '-var-file=../conf/lambda.json', '-destroy']
> StreamAlertCLI [INFO]: Completed

This leaves S3 buckets in my account but when attempting `python manage.py terraform destroy` it throws the same error and does not remove anything.

## Desired Change

This should support more than just the default us-east-1 region.

**Comment by jacknagz** [comment]
@scrapbird can you give some more context?

The paste you provided looks like a destroy and not an init.  Which regions are the buckets in?

**Comment by scrapbird** [comment]
My ap

**Comment by scrapbird** [comment]
My apologies, I actually pasted the wrong log.

Here is the correct one:

> StreamAlertCLI [INFO]: Issues? Report here: https://github.com/airbnb/streamalert/issues
> StreamAlertCLI [INFO]: Initializing StreamAlert
> StreamAlertCLI [INFO]: Initializing Terraform
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> 
> Terraform has been successfully initialized!
> 
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> 
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
> StreamAlertCLI [INFO]: Building Initial Infrastructure
> StreamAlertCLI [INFO]: Planning infrastructure
> provider.aws.region
>   The region where AWS operations will take place. Examples
>   are us-east-1, us-west-2, etc.
> 
>   Default: us-east-1
>   Enter a value: ap-southeast-2
> 
> Refreshing Terraform state in-memory prior to plan...
> The refreshed state will be used to calculate this plan, but will not be
> persisted to local or remote state storage.
> 
> aws_s3_bucket.terraform_remote_state: Refreshing state... (ID: [REDACTED].streamalert.terraform.state)
> aws_s3_bucket.logging_bucket: Refreshing state... (ID: [REDACTED].streamalert.s3-logging)
> aws_s3_bucket.lambda_source: Refreshing state... (ID: [REDACTED].streamalert.source)
> aws_s3_bucket.streamalerts: Refreshing state... (ID: [REDACTED].streamalerts)
> aws_s3_bucket.stream_alert_secrets: Refreshing state... (ID: [REDACTED].streamalert.secrets)
> aws_kms_key.stream_alert_secrets: Refreshing state... (ID: 4ea9b097-a84d-4a1f-8fcb-542d759b7a16)
> aws_kms_alias.stream_alert_secrets: Refreshing state... (ID: alias/stream_alert_secrets)
> 
> ------------------------------------------------------------------------
> 
> An execution plan has been generated and is shown below.
> Resource actions are indicated with the following symbols:
>   ~ update in-place
> 
> Terraform will perform the following actions:
> 
>   ~ aws_s3_bucket.terraform_remote_state
>       logging.#:                        "0" => "1"
>       logging.3809752855.target_bucket: "" => "[REDACTED].streamalert.s3-logging"
>       logging.3809752855.target_prefix: "" => "[REDACTED].streamalert.terraform.state/"
> 
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> 
> ------------------------------------------------------------------------
> 
> Note: You didn't specify an "-out" parameter to save this plan, so Terraform
> can't guarantee that exactly these actions will be performed if
> "terraform apply" is subsequently run.
> 
> 
> Would you like to continue? (yes or no): yes
> StreamAlertCLI [INFO]: Creating infrastructure
> provider.aws.region
>   The region where AWS operations will take place. Examples
>   are us-east-1, us-west-2, etc.
> 
>   Default: us-east-1
>   Enter a value: ap-southeast-2
> 
> aws_s3_bucket.lambda_source: Refreshing state... (ID: [REDACTED].streamalert.source)
> aws_kms_key.stream_alert_secrets: Refreshing state... (ID: 4ea9b097-a84d-4a1f-8fcb-542d759b7a16)
> aws_s3_bucket.logging_bucket: Refreshing state... (ID: [REDACTED].streamalert.s3-logging)
> aws_s3_bucket.stream_alert_secrets: Refreshing state... (ID: [REDACTED].streamalert.secrets)
> aws_s3_bucket.streamalerts: Refreshing state... (ID: [REDACTED].streamalerts)
> aws_s3_bucket.terraform_remote_state: Refreshing state... (ID: [REDACTED].streamalert.terraform.state)
> aws_kms_alias.stream_alert_secrets: Refreshing state... (ID: alias/stream_alert_secrets)
> aws_s3_bucket.terraform_remote_state: Modifying... (ID: [REDACTED].streamalert.terraform.state)
>   logging.#:                        "0" => "1"
>   logging.3809752855.target_bucket: "" => "[REDACTED].streamalert.s3-logging"
>   logging.3809752855.target_prefix: "" => "[REDACTED].streamalert.terraform.state/"
>   versioning.0.enabled:             "false" => "true"
> aws_s3_bucket.terraform_remote_state: Modifications complete after 7s (ID: [REDACTED].streamalert.terraform.state)
> 
> Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
> 
> The state of your infrastructure has been saved to the path
> below. This state is required to modify and destroy your
> infrastructure, so keep it safe. To inspect the complete state
> use the `terraform show` command.
> 
> State path: terraform.tfstate
> StreamAlertCLI [INFO]: Configuring Terraform Remote State
> Downloading modules...
> Get: file:///Users/bmorris/Software/streamalert/terraform/modules/tf_stream_alert_cloudtrail
> Get: file:///Users/bmorris/Software/streamalert/terraform/modules/tf_stream_alert_monitoring
> Get: file:///Users/bmorris/Software/streamalert/terraform/modules/tf_stream_alert_kinesis_events
> Get: file:///Users/bmorris/Software/streamalert/terraform/modules/tf_stream_alert_kinesis_streams
> Get: file:///Users/bmorris/Software/streamalert/terraform/modules/tf_stream_alert
> 
> Initializing the backend...
> Backend configuration changed!
> 
> Terraform has detected that the configuration specified for the backend
> has changed. Terraform will now reconfigure for this backend. If you didn't
> intend to reconfigure your backend please undo any changes to the "backend"
> section in your Terraform configuration.
> 
> 
> Error inspecting state in "s3": BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region
> 	status code: 301, request id: , host id:
> 
> Prior to changing backends, Terraform inspects the source and destination
> states to determine what kind of migration steps need to be taken, if any.
> Terraform failed to load the states. The data in both the source and the
> destination remain unmodified. Please resolve the above error and try again.
> StreamAlertCLI [ERROR]: An error occurred while running: terraform init
> ['terraform', 'init', '-force-copy']
> StreamAlertCLI [INFO]: Completed

**Comment by scrapbird** [comment]
Disregard, seems I left a configuration option in my config files pointing to us-east-1
