### ISSUE TITLE
terraform init fails with ResourceNotFoundException: Function not found

### ISSUE THREAD

**Issue by scrapbird** [airbnb/streamalert#473]
## Background

When launching a streamalert stack in us-east-1 (default) everything works fine. When launching in ap-southeast-2 (Sydney region) the `python manage.py terraform init` step fails when configuring the lambda functions. Lambda functions are created but then fails with the following error:

>Error creating Lambda alias: ResourceNotFoundException: Function not found: arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_rule_processor:2

Full log:

> (venv) ➜  streamalert git:(master) ✗ python manage.py terraform init
> StreamAlertCLI [INFO]: Issues? Report here: https://github.com/airbnb/streamalert/issues
> StreamAlertCLI [INFO]: Initializing StreamAlert
> StreamAlertCLI [INFO]: Initializing Terraform
> Downloading modules...
> 
> Initializing the backend...
> Backend configuration changed!
> 
> Terraform has detected that the configuration specified for the backend
> has changed. Terraform will now reconfigure for this backend. If you didn't
> intend to reconfigure your backend please undo any changes to the "backend"
> section in your Terraform configuration.
> 
> 
> 
> Successfully configured the backend "local"! Terraform will automatically
> use this backend unless the backend configuration changes.
> 
> Initializing provider plugins...
> 
> Terraform has been successfully initialized!
> 
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> 
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
> StreamAlertCLI [INFO]: Building Initial Infrastructure
> StreamAlertCLI [INFO]: Planning infrastructure
> provider.aws.region
>   The region where AWS operations will take place. Examples
>   are us-east-1, us-west-2, etc.
> 
>   Default: us-east-1
>   Enter a value: ap-southeast-2
> 
> Refreshing Terraform state in-memory prior to plan...
> The refreshed state will be used to calculate this plan, but will not be
> persisted to local or remote state storage.
> 
> aws_s3_bucket.logging_bucket: Refreshing state... (ID: [REDACTED].streamalert.s3-logging)
> aws_s3_bucket.terraform_remote_state: Refreshing state... (ID: [REDACTED].streamalert.terraform.state)
> aws_s3_bucket.lambda_source: Refreshing state... (ID: [REDACTED].streamalert.source)
> aws_s3_bucket.stream_alert_secrets: Refreshing state... (ID: [REDACTED].streamalert.secrets)
> aws_s3_bucket.streamalerts: Refreshing state... (ID: [REDACTED].streamalerts)
> aws_kms_key.stream_alert_secrets: Refreshing state... (ID: 64abbc9f-7257-452d-b296-3f460d1568fe)
> aws_kms_alias.stream_alert_secrets: Refreshing state... (ID: alias/stream_alert_secrets)
> 
> ------------------------------------------------------------------------
> 
> No changes. Infrastructure is up-to-date.
> 
> This means that Terraform did not detect any differences between your
> configuration and real physical resources that exist. As a result, no
> actions need to be performed.
> 
> Would you like to continue? (yes or no): yes
> StreamAlertCLI [INFO]: Creating infrastructure
> provider.aws.region
>   The region where AWS operations will take place. Examples
>   are us-east-1, us-west-2, etc.
> 
>   Default: us-east-1
>   Enter a value: ap-southeast-2
> 
> aws_s3_bucket.terraform_remote_state: Refreshing state... (ID: [REDACTED].streamalert.terraform.state)
> aws_s3_bucket.stream_alert_secrets: Refreshing state... (ID: [REDACTED].streamalert.secrets)
> aws_s3_bucket.lambda_source: Refreshing state... (ID: [REDACTED].streamalert.source)
> aws_s3_bucket.streamalerts: Refreshing state... (ID: [REDACTED].streamalerts)
> aws_kms_key.stream_alert_secrets: Refreshing state... (ID: 64abbc9f-7257-452d-b296-3f460d1568fe)
> aws_s3_bucket.logging_bucket: Refreshing state... (ID: [REDACTED].streamalert.s3-logging)
> aws_kms_alias.stream_alert_secrets: Refreshing state... (ID: alias/stream_alert_secrets)
> 
> Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
> StreamAlertCLI [INFO]: Configuring Terraform Remote State
> Downloading modules...
> 
> Initializing the backend...
> Backend configuration changed!
> 
> Terraform has detected that the configuration specified for the backend
> has changed. Terraform will now reconfigure for this backend. If you didn't
> intend to reconfigure your backend please undo any changes to the "backend"
> section in your Terraform configuration.
> 
> 
> 
> Successfully configured the backend "s3"! Terraform will automatically
> use this backend unless the backend configuration changes.
> 
> Initializing provider plugins...
> 
> Terraform has been successfully initialized!
> 
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> 
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
> StreamAlertCLI [INFO]: Deploying Lambda Functions
> StreamAlertCLI [INFO]: Creating package for rule_processor
> StreamAlertCLI [INFO]: Installing third-party libraries: backoff, jsonpath_rw, netaddr
> StreamAlertCLI [INFO]: Package successfully created
> StreamAlertCLI [INFO]: Uploading StreamAlert package to S3
> StreamAlertCLI [INFO]: Creating package for alert_processor
> StreamAlertCLI [INFO]: Installing third-party libraries: requests
> StreamAlertCLI [INFO]: Package successfully created
> StreamAlertCLI [INFO]: Uploading StreamAlert package to S3
> StreamAlertCLI [INFO]: Planning infrastructure
> provider.aws.region
>   The region where AWS operations will take place. Examples
>   are us-east-1, us-west-2, etc.
> 
>   Default: us-east-1
>   Enter a value: ap-southeast-2
> 
> Refreshing Terraform state in-memory prior to plan...
> The refreshed state will be used to calculate this plan, but will not be
> persisted to local or remote state storage.
> 
> aws_kms_key.stream_alert_secrets: Refreshing state... (ID: 64abbc9f-7257-452d-b296-3f460d1568fe)
> aws_cloudwatch_log_group.rule_processor: Refreshing state... (ID: /aws/lambda/[REDACTED]_prod_streamalert_rule_processor)
> aws_cloudwatch_log_group.alert_processor: Refreshing state... (ID: /aws/lambda/[REDACTED]_prod_streamalert_alert_processor)
> data.aws_iam_policy_document.alert_processor_cloudwatch: Refreshing state...
> data.aws_iam_policy_document.rule_processor_kms_decrypt: Refreshing state...
> data.aws_iam_policy_document.lambda_assume_role_policy: Refreshing state...
> data.aws_iam_policy_document.streamalert_rule_processor_firehose: Refreshing state...
> data.aws_iam_policy_document.rule_processor_invoke_alert_proc: Refreshing state...
> data.aws_iam_policy_document.alert_processor_s3: Refreshing state...
> aws_iam_role.streamalert_rule_processor_role: Refreshing state... (ID: [REDACTED]_prod_streamalert_rule_processor_role)
> aws_iam_role.streamalert_alert_processor_role: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_processor_role)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[1]: Refreshing state... (ID: RuleProcessor-TotalRecords)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[16]: Refreshing state... (ID: RuleProcessor-TotalProcessedSize-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[15]: Refreshing state... (ID: RuleProcessor-TriggeredAlerts)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[6]: Refreshing state... (ID: RuleProcessor-FailedParses-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[2]: Refreshing state... (ID: RuleProcessor-TotalS3Records-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[9]: Refreshing state... (ID: RuleProcessor-TotalStreamAlertAppRecords)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[8]: Refreshing state... (ID: RuleProcessor-TotalStreamAlertAppRecords-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[7]: Refreshing state... (ID: RuleProcessor-FailedParses)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[5]: Refreshing state... (ID: RuleProcessor-FirehoseRecordsSent)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[17]: Refreshing state... (ID: RuleProcessor-TotalProcessedSize)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[13]: Refreshing state... (ID: RuleProcessor-FirehoseFailedRecords)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[10]: Refreshing state... (ID: RuleProcessor-S3DownloadTime-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[3]: Refreshing state... (ID: RuleProcessor-TotalS3Records)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[4]: Refreshing state... (ID: RuleProcessor-FirehoseRecordsSent-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[0]: Refreshing state... (ID: RuleProcessor-TotalRecords-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[12]: Refreshing state... (ID: RuleProcessor-FirehoseFailedRecords-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[14]: Refreshing state... (ID: RuleProcessor-TriggeredAlerts-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[11]: Refreshing state... (ID: RuleProcessor-S3DownloadTime)
> aws_iam_role_policy.streamalert_alert_processor_s3: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_proces...streamalert_alert_processor_s3_default)
> aws_lambda_function.streamalert_alert_processor: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_processor)
> aws_iam_role_policy.streamalert_alert_processor_kms: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_proces...s_prod_streamalert_alert_processor_kms)
> aws_iam_role_policy.streamalert_alert_processor_cloudwatch: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_proces...streamalert_alert_processor_cloudwatch)
> aws_iam_role_policy.streamalert_rule_processor_lambda: Refreshing state... (ID: [REDACTED]_prod_streamalert_rule_process...alert_rule_processor_invoke_alert_proc)
> aws_lambda_function.streamalert_rule_processor: Refreshing state... (ID: [REDACTED]_prod_streamalert_rule_processor)
> aws_iam_role_policy.streamalert_rule_processor_firehose: Refreshing state... (ID: [REDACTED]_prod_streamalert_rule_process...od_streamalert_rule_processor_firehose)
> 
> ------------------------------------------------------------------------
> 
> An execution plan has been generated and is shown below.
> Resource actions are indicated with the following symbols:
>   + create
>   ~ update in-place
> 
> Terraform will perform the following actions:
> 
>   + module.stream_alert_prod.aws_lambda_alias.alert_processor_production
>       id:               <computed>
>       arn:              <computed>
>       description:      "Production StreamAlert Alert Processor Alias"
>       function_name:    "arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_alert_processor"
>       function_version: "2"
>       name:             "production"
> 
>   + module.stream_alert_prod.aws_lambda_alias.rule_processor_production
>       id:               <computed>
>       arn:              <computed>
>       description:      "Production StreamAlert Rule Processor Alias"
>       function_name:    "arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_rule_processor"
>       function_version: "2"
>       name:             "production"
> 
>   ~ module.stream_alert_prod.aws_lambda_function.streamalert_alert_processor
>       s3_key:           "alert_processor/alert_processor_1.5.0_20171113_T222737.zip" => "alert_processor/alert_processor_1.5.0_20171113_T235725.zip"
> 
>   ~ module.stream_alert_prod.aws_lambda_function.streamalert_rule_processor
>       s3_key:           "rule_processor/rule_processor_1.5.0_20171113_T222731.zip" => "rule_processor/rule_processor_1.5.0_20171113_T235721.zip"
> 
>   + module.stream_alert_prod.aws_lambda_permission.rule_processor
>       id:               <computed>
>       action:           "lambda:InvokeFunction"
>       function_name:    "arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_alert_processor"
>       principal:        "lambda.amazonaws.com"
>       qualifier:        "production"
>       source_arn:       "arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_rule_processor"
>       statement_id:     "AllowExecutionFromLambda"
> 
> 
> Plan: 3 to add, 2 to change, 0 to destroy.
> 
> ------------------------------------------------------------------------
> 
> Note: You didn't specify an "-out" parameter to save this plan, so Terraform
> can't guarantee that exactly these actions will be performed if
> "terraform apply" is subsequently run.
> 
> 
> Would you like to continue? (yes or no): yes
> StreamAlertCLI [INFO]: Creating infrastructure
> provider.aws.region
>   The region where AWS operations will take place. Examples
>   are us-east-1, us-west-2, etc.
> 
>   Default: us-east-1
>   Enter a value: ap-southeast-2
> 
> aws_kms_key.stream_alert_secrets: Refreshing state... (ID: 64abbc9f-7257-452d-b296-3f460d1568fe)
> aws_cloudwatch_log_group.alert_processor: Refreshing state... (ID: /aws/lambda/[REDACTED]_prod_streamalert_alert_processor)
> aws_cloudwatch_log_group.rule_processor: Refreshing state... (ID: /aws/lambda/[REDACTED]_prod_streamalert_rule_processor)
> data.aws_iam_policy_document.rule_processor_invoke_alert_proc: Refreshing state...
> data.aws_iam_policy_document.streamalert_rule_processor_firehose: Refreshing state...
> data.aws_iam_policy_document.lambda_assume_role_policy: Refreshing state...
> data.aws_iam_policy_document.alert_processor_cloudwatch: Refreshing state...
> data.aws_iam_policy_document.rule_processor_kms_decrypt: Refreshing state...
> data.aws_iam_policy_document.alert_processor_s3: Refreshing state...
> aws_iam_role.streamalert_rule_processor_role: Refreshing state... (ID: [REDACTED]_prod_streamalert_rule_processor_role)
> aws_iam_role.streamalert_alert_processor_role: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_processor_role)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[11]: Refreshing state... (ID: RuleProcessor-S3DownloadTime)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[4]: Refreshing state... (ID: RuleProcessor-FirehoseRecordsSent-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[16]: Refreshing state... (ID: RuleProcessor-TotalProcessedSize-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[7]: Refreshing state... (ID: RuleProcessor-FailedParses)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[6]: Refreshing state... (ID: RuleProcessor-FailedParses-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[5]: Refreshing state... (ID: RuleProcessor-FirehoseRecordsSent)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[0]: Refreshing state... (ID: RuleProcessor-TotalRecords-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[10]: Refreshing state... (ID: RuleProcessor-S3DownloadTime-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[8]: Refreshing state... (ID: RuleProcessor-TotalStreamAlertAppRecords-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[17]: Refreshing state... (ID: RuleProcessor-TotalProcessedSize)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[15]: Refreshing state... (ID: RuleProcessor-TriggeredAlerts)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[12]: Refreshing state... (ID: RuleProcessor-FirehoseFailedRecords-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[14]: Refreshing state... (ID: RuleProcessor-TriggeredAlerts-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[9]: Refreshing state... (ID: RuleProcessor-TotalStreamAlertAppRecords)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[2]: Refreshing state... (ID: RuleProcessor-TotalS3Records-PROD)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[1]: Refreshing state... (ID: RuleProcessor-TotalRecords)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[13]: Refreshing state... (ID: RuleProcessor-FirehoseFailedRecords)
> aws_cloudwatch_log_metric_filter.rule_processor_cw_metric_filters[3]: Refreshing state... (ID: RuleProcessor-TotalS3Records)
> aws_iam_role_policy.streamalert_rule_processor_lambda: Refreshing state... (ID: [REDACTED]_prod_streamalert_rule_process...alert_rule_processor_invoke_alert_proc)
> aws_lambda_function.streamalert_rule_processor: Refreshing state... (ID: [REDACTED]_prod_streamalert_rule_processor)
> aws_iam_role_policy.streamalert_rule_processor_firehose: Refreshing state... (ID: [REDACTED]_prod_streamalert_rule_process...od_streamalert_rule_processor_firehose)
> aws_iam_role_policy.streamalert_alert_processor_cloudwatch: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_proces...streamalert_alert_processor_cloudwatch)
> aws_iam_role_policy.streamalert_alert_processor_s3: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_proces...streamalert_alert_processor_s3_default)
> aws_iam_role_policy.streamalert_alert_processor_kms: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_proces...s_prod_streamalert_alert_processor_kms)
> aws_lambda_function.streamalert_alert_processor: Refreshing state... (ID: [REDACTED]_prod_streamalert_alert_processor)
> module.stream_alert_prod.aws_lambda_function.streamalert_rule_processor: Modifying... (ID: [REDACTED]_prod_streamalert_rule_processor)
>   s3_key: "rule_processor/rule_processor_1.5.0_20171113_T222731.zip" => "rule_processor/rule_processor_1.5.0_20171113_T235721.zip"
> module.stream_alert_prod.aws_lambda_function.streamalert_alert_processor: Modifying... (ID: [REDACTED]_prod_streamalert_alert_processor)
>   s3_key: "alert_processor/alert_processor_1.5.0_20171113_T222737.zip" => "alert_processor/alert_processor_1.5.0_20171113_T235725.zip"
> module.stream_alert_prod.aws_lambda_function.streamalert_rule_processor: Modifications complete after 1s (ID: [REDACTED]_prod_streamalert_rule_processor)
> module.stream_alert_prod.aws_lambda_alias.rule_processor_production: Creating...
>   arn:              "" => "<computed>"
>   description:      "" => "Production StreamAlert Rule Processor Alias"
>   function_name:    "" => "arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_rule_processor"
>   function_version: "" => "2"
>   name:             "" => "production"
> module.stream_alert_prod.aws_lambda_function.streamalert_alert_processor: Modifications complete after 1s (ID: [REDACTED]_prod_streamalert_alert_processor)
> module.stream_alert_prod.aws_lambda_alias.alert_processor_production: Creating...
>   arn:              "" => "<computed>"
>   description:      "" => "Production StreamAlert Alert Processor Alias"
>   function_name:    "" => "arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_alert_processor"
>   function_version: "" => "2"
>   name:             "" => "production"
> Error applying plan:
> 
> 2 error(s) occurred:
> 
> * module.stream_alert_prod.aws_lambda_alias.rule_processor_production: 1 error(s) occurred:
> 
> * aws_lambda_alias.rule_processor_production: Error creating Lambda alias: ResourceNotFoundException: Function not found: arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_rule_processor:2
> 	status code: 404, request id: 95698cdc-c8ce-11e7-8646-81e548922c84
> * module.stream_alert_prod.aws_lambda_alias.alert_processor_production: 1 error(s) occurred:
> 
> * aws_lambda_alias.alert_processor_production: Error creating Lambda alias: ResourceNotFoundException: Function not found: arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_alert_processor:2
> 	status code: 404, request id: 956bd6a9-c8ce-11e7-b3ba-8f150c8ef90b
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
> StreamAlertCLI [ERROR]: An error occurred while running: terraform apply -var-file=../conf/lambda.json -target=module.stream_alert_prod
> ['terraform', 'apply', '-var-file=../conf/lambda.json', '-target=module.stream_alert_prod']

## Desired Change

Init to finish running.

**Comment by jacknagz** [comment]
did you reset the version in the cluster when you went from us-east-1 to ap-southeast?

```
Error creating Lambda alias: ResourceNotFoundException: Function not found: arn:aws:lambda:ap-southeast-2:[REDACTED]:function:[REDACTED]_prod_streamalert_rule_processor:2
```

in your cluster config, change:

```
    "stream_alert": {
      "alert_processor": {
        ...
        "current_version": 2,
      },
      "rule_processor": {
        ...
        "current_version": 2,
      }
    }
```

to

```
    "stream_alert": {
      "alert_processor": {
        ...
        "current_version": "$LATEST"
      },
      "rule_processor": {
        ...
        "current_version": "$LATEST"
      }
    }
```

**Comment by scrapbird** [comment]
Hah, solves my issue. Thanks for the fast response 👍

**Comment by jacknagz** [comment]
@scrapbird feel free to ping us on slack in the future 😄

**Comment by scrapbird** [comment]
@jacknagz I will join now :)
