### ISSUE TITLE
Bug: backend generation ignores the teraform.tfstate_bucket config in global.json

### ISSUE THREAD

**Issue by kmosher** [airbnb/streamalert#523]
### Description

The generate_main() function in generate.py names the terraform state backend based on the configured prefix. This happens even though there's a separate config block in `global.json` laying out the bucket and path remote state should reside at.

### Steps to Reproduce

Change `terraform.tfstate_bucket` or `terraform.tfstate_s3_key` in `conf/global.json` then run `python manage.py terraform init`. Terraform will create the new bucket, but continue writing state to the old s3 path.

## Desired Change

Have `terraform/generate.py` key off the relevant config  #options.

**Comment by jacknagz** [comment]
Thanks @kmosher, @javuto will take a look into this

**Comment by austinbyers** [comment]
Fixed by #770
