### ISSUE TITLE
Improvement: allow another aws account to assume the iam role that has write access to a kinesis stream

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#574]
## Background

From: xinghong.fang

### Description

New feature suggest: “allow another aws account to assume the iam role that has write access to a kinesis stream”.

I think this will be useful as log collectors running on other aws account can assume the kinesis_writeonly role to write logs to it without having to provide iam user credential. I have some rough idea on how to implement this, let me know if you are interested

it looks roughly like this in the cluster config file:

```
    "kinesis": {
      "streams": {
        "retention": 24,
        "shards": 1,
        "trusted_account": "12345678"
      }
    },
```

the default will be “”, and terraform will only create the role if the value is non-empty

**Comment by pchaganti** [comment]
👍

**Comment by javefang** [comment]
For each cluster, do we want to support multiple trusted_account? i.e. allow multiple aws account to write to a single kinesis stream?
