### ISSUE TITLE
Improve "Quick Start" Documentation

### ISSUE THREAD

**Issue by austinbyers** [airbnb/streamalert#576]
## Background

The [Quick Start](https://streamalert.io/getting-started.html#quick-start) documentation just points you to 9 different pages. Thus, in order to "get started" with StreamAlert, you first have to read through half of the documentation.

## Desired Change

I would love a "Getting Started" page which outlines (on a single page) the minimum number of steps for someone to get StreamAlert up and running. For example, creating an S3 bucket and configuring it as an event source, then sending CloudTrail data there. Something quick and tangible that people can use to easily try it.

**Comment by jacknagz** [comment]
@austinbyers did you happen to see the `clusters` page? It includes example cluster's, one of which includes S3 processing via CloudTrail

**Comment by austinbyers** [comment]
Right, but how would someone know all they need to do is add that cluster definition? Some examples require defining inputs as well, for example. And even then the path is Getting Started => Clusters => (choose one of the examples) => Deployment, and it's not clear what someone would be looking for to see if it works.

I just envision a single page which gets you from a blank machine to a StreamAlert deployment. Example in the BinaryAlert documentation: https://binaryalert.io/getting-started.html

**Comment by jacknagz** [comment]
@austinbyers I agree, but I think the CLI needs to improve more before that can be reality.  I'd love to see all the config interaction just be with commands vs modifying JSON, then it becomes much simpler to just instruct a user to type commands to get started.

**Comment by chilithomas** [comment]
https://streamalert.readthedocs.io/ really helped with initial quick start and deployment but I'd like to see more for setting up alerts.

**Comment by libertyy** [comment]
It wasn't clear in getting started  docs that in addition to running `python manage.py output new --service slack`, i had to then update rules/ files to send alerts into Slack.

**Comment by ryandeivert** [comment]
closing this since it's fairly outdated the and these concerns have been largely addressed
