### ISSUE TITLE
Feature: Github output

### ISSUE THREAD

**Issue by patrickod** [airbnb/streamalert#586]
## Background

We use Github issues extensively to track work outside of the scope of any particular repository in our organization, including non-code processes. To that end we'd love to support Github issue outputs from Steamalert alerts to allow them to be more closely integrated into our existing workflows. 

## Desired Change

Support the creation of Github issues from alerts. Each new alert would create its own Github issue, though future work might facilitate the grouping of alerts into issues based potentially on labels or other factors.

**Comment by austinbyers** [comment]
Great idea! We may not be able to do this for a while, but we welcome pull requests!

**Comment by patrickod** [comment]
@austinbyers I have a WIP branch @ https://github.com/patrickod/streamalert/tree/patrickod/add-github-output that I'll be testing this week that adds this functionality. Hope to have it PR-worthy in the coming days.
