### ISSUE TITLE
Terraform 0.11.X Support

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#609]
### Description

StreamAlert is currently pinned to version 0.10.X of Terraform, the newest version is 0.11.3

### Steps to Reproduce

Run through initialization via `$ python manage.py terraform init`

## Desired Change

* Upgrade Terraform
* Remove the custom check for continuing during each build step

**Comment by javefang** [comment]
Hi, we've been using 0.11.3 fine for a while by changing this line to 0.11.0
https://github.com/airbnb/streamalert/blob/master/stream_alert_cli/terraform/generate.py#L45

But more testing might be required.

Also we achieved "remove the custom check" by doing this trick
`$ yes yes | python manage.py terraform build`
(but this will not pause even after terraform plan which is not nice)

**Comment by m6a-UdS** [comment]
I managed to make it work using 0.11.4, but the initial deployment necessitates changes in https://github.com/airbnb/streamalert/blob/master/terraform/modules/tf_lambda/output.tf

Lines 3 and 8 need to use the `splat syntax` so I changed them to:
`"${aws_lambda_function.function_vpc.*.arn}"`
and
`"${aws_lambda_function.function_no_vpc.*.arn}"`

I also get warnings for lines 12 and 16 but the code still works... I am really a newbie with Terraform, but I hope this helps :-)
