### ISSUE TITLE
Bug: Documentation search is broken

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#63]
**Reproduction steps**:

Load https://www.streamalert.io/search.html?q=account&check_keywords=yes&area=default
Click on any result

**Details**:

The links oddly end in .rst.html

Example: https://www.streamalert.io/account.rst.html

It should be https://www.streamalert.io/account.html

**Fix**:

Waiting on https://github.com/rtfd/readthedocs.org/issues/2708

**Comment by strcrzy** [comment]
might be this -- http://www.sphinx-doc.org/en/stable/config.html#confval-html_link_suffix

**Comment by strcrzy** [comment]
maybe not. but there's a clue [here](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/docs_resolv.py#L238-L241) --
```
     # In 1.5+ Sphinx seems to have changed from .rst.html to only
     # .html extension in converted files. But URLs could be
     # built with < 1.5 or >= 1.5 regardless of what we're currently
     # building with, so let's just check both :(
```

**Comment by mime-frame** [comment]
This was resolved via https://github.com/airbnb/streamalert/pull/112
