### ISSUE TITLE
Improve error handling of non-json sent to kinesis stream.

### ISSUE THREAD

**Issue by 0xdabbad00** [airbnb/streamalert#648]
## Background

Have you tried pinging us on Slack? No
Are you on the latest version of StreamAlert? Yes

### Description

I was testing something and sent the string "hello" as a record to my Kinesis Stream.  StreamAlert kept error'ing every time it tried to read from the stream, due to an `AttributeError` here: https://github.com/airbnb/streamalert/blob/a97fb604f0d6498219f3599f786745fd7544c992/stream_alert/rule_processor/parsers.py#L154

Full crash was:
```
'unicode' object has no attribute 'keys': AttributeError
Traceback (most recent call last):
File "/var/task/stream_alert/rule_processor/main.py", line 59, in handler
StreamAlert(context).run(event)
File "/var/task/stream_alert/rule_processor/handler.py", line 121, in run
payload_with_normalized_records.extend(self._process_alerts(payload))
File "/var/task/stream_alert/rule_processor/handler.py", line 178, in _process_alerts
self.classifier.classify_record(record)
File "/var/task/stream_alert/shared/stats.py", line 27, in timed
result = func(*args, **kw)
File "/var/task/stream_alert/rule_processor/classifier.py", line 140, in classify_record
parse_result = self._parse(payload)
File "/var/task/stream_alert/rule_processor/classifier.py", line 257, in _parse
schema_matches = self._process_log_schemas(payload)
File "/var/task/stream_alert/shared/stats.py", line 27, in timed
result = func(*args, **kw)
File "/var/task/stream_alert/rule_processor/classifier.py", line 226, in _process_log_schemas
parsed_data = parser.parse(schema, payload.pre_parsed_record)
File "/var/task/stream_alert/shared/stats.py", line 27, in timed
result = func(*args, **kw)
File "/var/task/stream_alert/rule_processor/parsers.py", line 324, in parse
if not self._key_check(schema, json_records):
File "/var/task/stream_alert/rule_processor/parsers.py", line 140, in _key_check
json_keys = set(json_records[index].keys())
AttributeError: 'unicode' object has no attribute 'keys'
```

Every time new data came into my Kinesis Stream, StreamAlert's rule lambda would trigger and attempt to read all the data in the stream, starting back at the point of this failure, causing yet another failure.  I suspect this would continue until the retention time of the data expired.

I eventually bypassed this by adding:
```
if type(json_records[index]) is unicode:
                LOGGER.info('Record was unicode, skipping')
                return False
```

This allowed StreamAlert to catch back up by skipping that record.  There could be better handled by checking if it is a `dict` probably and skipping otherwise.

### Steps to Reproduce

Do a `put-record` against your stream of just `hello`.  You're StreamAlert setup will no longer be able to evaluate anymore incoming records until the retention of the data expires.

## Desired Change

Add error handling to skip malformed records and record somehow that malformed data was received so it can be investigated without blocking all other records.

I don't know if this is by design, so let me describe the two options:
1. Keep things as they are.  This means you block on bad data so someone can fix the problem and that record and all records after that which are similarly malformed could be handled correctly.  The negative is no records will be evaluated until this is resolved.
2. Skip the malformed record.  The negative of this is that potentially valuable records will be skipped and cannot easily be re-evaluated.  The positive is that your StreamAlert setup continues functioning for other records.

I prefer Option 2.

**Comment by ryandeivert** [comment]
hey @0xdabbad00 - If you'd like to put a PR up for this that would be great! I'd suggest going to route of skipping the malformed records (as you suggest in #2).

to your point about missing the records and not re-evaluating them, that's not much different than how a non-classifiable log acts now anyway. if a failed parse occurs for a log, there is no retry and the failure is just logged.

I would also recommend using the `dict` check instead of the `unicode` check. But please use:
`not isinstance(json_records[index], dict)`

One last request would be using a `LOGGER.error` statements instead to so it's easily searchable.

thanks for filing this!

**Comment by 0xdabbad00** [comment]
Unable to reproduce, so I've closed this.
