### ISSUE TITLE
Support Required Subkeys for Matchers

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#658]
### Description

When using loose schemas, it's recommended to use the `req_subkeys` keyword argument to avoid `KeyErrors`.   This works by introspecting incoming records, and using criteria to assert whether or not the record has the appropriate fields referenced in the rule.

This logic does not exist in `matchers`, which can be applied to multiple rules.  As a result, the user needs to declare subkeys used in the matcher in every rule's `req_subkeys` argument.  This adds a lot of unnecessary overhead.

## Desired Change

Support `req_subkeys` functionality in the `matcher` decorator

**Comment by ryandeivert** [comment]
won't fix
