### ISSUE TITLE
aws_cloudtrail always sees a change for event_selector

### ISSUE THREAD

**Issue by roman-vynar** [airbnb/streamalert#668]
## Description

TF always sees a change for `aws_cloudtrail` resource due to `event_selector` statement.
```
resource "aws_cloudtrail" "cloudtrail-general" {
  name                          = "cloudtrail-general"
  s3_bucket_name                = "foobar-bucket"
  is_multi_region_trail         = true
  include_global_service_events = true
  enable_log_file_validation    = true

  event_selector {
    read_write_type           = "All"
    include_management_events = true
  }
}
```

### Steps to Reproduce
Once the above is created/re-applied there is a persistent change:
```
  ~ aws_cloudtrail.cloudtrail-general
      event_selector.#:                           "0" => "1"
      event_selector.0.include_management_events: "" => "true"
      event_selector.0.read_write_type:           "" => "All"
```
## Desired Change
There shouldn't be any pending changes once the above is applied.

**Comment by roman-vynar** [comment]
Sorry wrong repo :D

**Comment by ryandeivert** [comment]
hey @roman-vynar I know you opened this on the wrong repo - but I think your resource is missing something extra. your default `event_selector` should include the `data_resource` to prevent tf from changing the resources that already exist in your account. like so:

```
  event_selector {
    read_write_type           = "All"
    include_management_events = true

    data_resource {
      type = "AWS::S3::Object"

      values = [
        "arn:aws:s3",
      ]
    }
  }
```

**Comment by roman-vynar** [comment]
Thanks @ryandeivert Looks like it's not needed at all when I am not going to log neither S3 ops nor Lambda ones 🍺
