### ISSUE TITLE
Bug: Multiple S3 Event Notifications From The Same Bucket

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#730]
### Description

When configuring S3 Event notifications, users have the option of specifying a Prefix filter.  This means that events will only be sent from a specific folder with S3 to invoke the rule processor.  Due to a limitation in Terraform, bucket notifications for a single bucket *cannot* be managed across resources, which means we cannot use the existing s3_events module to manage a single bucket with multiple prefixes.

### Steps to Reproduce

Try to use the `s3_events` module within a single cluster, with a single bucket, across two different prefixes:

```json
{
  "id": "cloudtrail_test",
  "modules": {
    "cloudwatch_monitoring": {
      "enabled": true,
      "kinesis_alarms_enabled": false
    },
    "s3_events": [
      {
        "bucket_id": "test.streamalert.cloudtrail",
        "enable_events": true,
        "filter_prefix": "AWSLogs/111111009933/"
      },
      {
        "bucket_id": "test.streamalert.cloudtrail",
        "enable_events": true,
        "filter_prefix": "AWSLogs/133555111111/"
      }
    ],
    "stream_alert": {
      "rule_processor": {
        "current_version": "$LATEST",
        "enable_metrics": true,
        "log_level": "info",
        "memory": 512,
        "timeout": 300
      }
    }
  },
  "outputs": {},
  "region": "us-east-1"
}
```

## Desired Change

There are a couple options to resolve this, one potential could be implementing a filtering mechanism into the rule processor.  I started work on this awhile ago, but haven't dedicated time to completing it: https://github.com/airbnb/streamalert/tree/jacknaglieri-classify-exclude-logic

The idea with this branch is that we could start to add exclusion logic into the rule processor, and then just notify on any object written to a bucket.

Another option could be generating a tf.json file for all possible prefixes from a given bucket.  This is probably the easiest solution.

**Comment by ryandeivert** [comment]
this is fixed with: https://github.com/airbnb/streamalert/pull/1051
