### ISSUE TITLE
Required subkey check fails when the subkey exists, but the value is false

### ISSUE THREAD

**Issue by stoggi** [airbnb/streamalert#787]
## Background

When using required subkeys in a rule, the subkey check fails if the subkey exists, but the value is `false`.

For example, in the test for critical_api_calls:
```
{
  "data":{
    "Records":[
      {
        ...
        "responseElements":{
          "storageEncrypted":false,
        }
        ...
      }
    ]
  },
  "description":"Deleting a database cluster (DeleteDBCluster) will create an alert.",
  "log":"cloudtrail:events",
  "service":"s3",
  "source":"prefix.cluster.sample.bucket",
  "trigger_rules":[
    "cloudtrail_critical_api_calls"
  ]
}
```
The subkey `storageEncrypted` will cause the rule not to run if included as a required subkey.

Using `stable`, but it looks like the issue would also be present on `master`.

### Description

The suspected piece of code is:
https://github.com/airbnb/streamalert/blob/6da3b52994ec4d4751245cdcf61ab23172de0670/stream_alert/rule_processor/rules_engine.py#L238

Because `record[key].get(x)` will return `false` if the key exists, but value is actually `false`. Then `all()` returns `false` for any values of `None` and `false`.

### Steps to Reproduce

1. Clone master
2. Verify all of the following tests pass
```
python manage.py lambda test -p rule -r cloudtrail_critical_api_calls
```
3. Modify the rule `cloudtrail_critical_api_calls` to include the following subkey, which does exist in the test, but is set to `false`.
```
@rule(logs=['cloudtrail:events'], req_subkeys={'responseElements':['storageEncrypted']})
def cloudtrail_critical_api_calls(rec):
```
4. Verify that all the tests fail, even though the test `Deleting a database cluster (DeleteDBCluster) will create an alert.` should have passed.
5. For extra credit, change the `storageEncrypted` value from `false` to `"abc"` and watch it pass

## Desired Change

A subkey with value `false` should still pass the req_subkey check.

**Comment by stoggi** [comment]
You could include a check for `None`:
```
if any(record[key].get(x) is None for x in nested_keys):
    return False
```

Although, `null` is allowed in the JSON spec, so you could still end up with a `None` value:
```
>>> json.loads("""{"a":"1","b":null}""")
{u'a': u'1', u'b': None}
```

So perhaps `key in dict` is better:
```
if any(x not in record[key] for x in nested_keys):
    return False
```

**Comment by ryandeivert** [comment]
thanks for list! the last example you give in [this comment](https://github.com/airbnb/streamalert/issues/787#issuecomment-403722534) would be the preferred fix 👍
