### ISSUE TITLE
errorCode logic not valid in rule cloudtrail_mfa_policy_abuse_attempt

### ISSUE THREAD

**Issue by stoggi** [airbnb/streamalert#803]
## Background

In the rule `cloudtrail_mfa_policy_abuse_attempt` the errorCode is not properly checked as part of the rule logic:

https://github.com/airbnb/streamalert/blob/d5c658fc73f5dad6c6577bd462a85f38102b1c10/rules/community/cloudtrail/cloudtrail_mfa_policy_abuse_attempt.py#L62-L70

It seems the intent is only to alert if there is any error for a `CreateVirtualMFADevice` or `EnableMFADevice` event. But because errorCode is specified in optional_top_level_keys, it actually gets assigned a default value of `str()`, even if there is no error.

https://github.com/airbnb/streamalert/blob/d7a879b9b463d9a304328e1d170a27f118ff5cb0/stream_alert/rule_processor/parsers.py#L245-L248

### Description

The `errorCode` key is always set in records, regardless of an error or not, so the rule logic is not valid.

### Steps to Reproduce

1. Sign into the AWS Console without MFA
2. Activate a new virtual MFA device
3. Observe the alert
4. For bonus points, check the event in CloudWatch to double check the actual event had no key `errorCode` in the event JSON.

## Desired Change

Modify the rule to check if errorCode is not an empty string

**Comment by strcrzy** [comment]
Thanks for reporting this! We will definitely fix this, but how would you feel about taking a crack at it?

**Comment by stoggi** [comment]
Sure, happy to submit a PR for this 👍
