### ISSUE TITLE
convert to python3

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#850]
## Background

While we still have a good amount of time until python2 is truly end-of-life/'unsupported', we should begin prioritizing migration to python3.

## Desired Change

Use `2to3` to convert to python3, update any dependencies, and fix any unit tests that break along the way.

**Comment by 0xdabbad00** [comment]
Python 2.7 is EOL'd by Python on January 1, 2020. AWS normally deprecates run-times at the same time as the upstream deprecation occurs, so we should expect the same to happen here (ie. StreamAlert needs to be updated to Python 3 before January 2020).

**Comment by ryandeivert** [comment]
conversion completed in #974
