### ISSUE TITLE
support customization of alert payload with fields/context

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#870]
related to: #305 

## Background

To enable faster triage, it would be ideal if users could have more control over the data that gets sent to alerting outputs (pagerduty, slack, etc).

## Desired Change

Support defining a custom 'alert output', either based globally on a log type or from within rules (or both). All alert outputs should support sending a 'consolidated' or 'custom' alert, if one is defined _except_ for the `firehose:alerts` output that should retain the original, unmodified record.

We/I can add more context as needed.

**Comment by srikiraju** [comment]
This is also useful if we want to redact some information that we think might be sensitive. Example: we have an alert for specific command lines being run that might potentially have sensitive information that we don't want to leak to pgduty/slack. It would be useful if we could construct just a custom alert message and leave the full alert in the firehose/s3 meant for athena.

**Comment by 0xdabbad00** [comment]
I believe this is now resolved by #900

**Comment by Ryxias** [comment]
Yup! This is exactly what Alert Publishers were supposed to do
