### ISSUE TITLE
Issue: Not all regions support firehose

### ISSUE THREAD

**Issue by zeroCrashOveride** [airbnb/streamalert#91]
Hey, Oblivious this is an AWS issue. The required kinesis firehouse resource's, are available in three regions: EU (Ireland), US East (N. Virginia) and US West (Oregon)

Advice, tips or workarounds welcome!

Cheers,
Andrew

**Comment by jacknagz** [comment]
@zeroCrashOveride We can add an option to the Terraform module which conditionally creates a Firehose.  Currently, the Lambda function does not write to Firehose, it must happen from the producers themselves.

**Comment by zeroCrashOveride** [comment]
Agreed on the Terraform point, For message streaming ( firehose resource ) worth having an option to swap with out for OSS techonogy like RabbitMQ, Kafka, Storm, Samza, Flink?

Until AWS get on the ball of course

**Comment by jacknagz** [comment]
@zeroCrashOveride You could add support for them as inputs if they can invoke Lambda!
