### ISSUE TITLE
[improvement] Detect non-compliant prefix names

### ISSUE THREAD

**Issue by 0xdabbad00** [airbnb/streamalert#939]
## Background

I asked in Slack, and chunyong.lin said to file an issue.  https://streamalert.slack.com/archives/C3BHE2Z0S/p1558129617101100

Are you on the latest version of StreamAlert? Yes

### Description

Prefix names must be alphanumeric. You are restricted from including underscores in the prefix name, not dashes.  When you try to init, things will break.

### Steps to Reproduce

./manage.py configure prefix scotts-streamalert
./manage.py init

## Desired Change

Check the prefix name when it is set to ensure it conforms to the required character set.

**Comment by xoob** [comment]
I encountered an error from S3 using `Testing`, but `testing` was accepted. Looks like prefixes must be all lower-case.

**Comment by ryandeivert** [comment]
fixed with #1272
