### ISSUE TITLE
[improvement] Add ability to over-write existing outputs

### ISSUE THREAD

**Issue by 0xdabbad00** [airbnb/streamalert#940]
## Background

Mentioned on Slack: https://streamalert.slack.com/archives/C3BHE2Z0S/p1558386389107200
Are you on the latest version of StreamAlert? Yes

### Description

If you configure a Slack webhook, and want to change it, then trying to rerun `./manage.py output slack` with the same name will result in an error.  Currently, you have to manually edit `conf/outputs.json` to remove the output and then retry that command.  It would be nice to have a way to over-write or delete the existing output.

### Steps to Reproduce

Run `./manage.py output slack` and configure an output.
Rerun the same command with the same output name and a new webhook URL and you'll get an error.

## Desired Change

Provide a `--override` to delete the current output and add the new one.

**Comment by Ryxias** [comment]
👍

**Comment by VinodKumarLogan** [comment]
Hi @0xdabbad00 @Ryxias , I'm interested in working on this feature. Can I please work on it and submit a PR?

**Comment by jack1902** [comment]
@0xdabbad00 Will add a PR for this feature for `release-3-1-0`

**Comment by 0xdabbad00** [comment]
@jack1902 I'm not sure if you meant to say that you will be adding this feature, but just to clarify, I unfortunately do not have the time to add it.

**Comment by jack1902** [comment]
@0xdabbad00 yeah sorry for the confusion. Coffee hadn't kicked in

**Comment by jack1902** [comment]
@0xdabbad00 I believe this issue can be closed at the `output` command has now got some new features :)

**Comment by 0xdabbad00** [comment]
Thanks @jack1902 !
