### ISSUE TITLE
Streamalert deployment; terraform init issue

### ISSUE THREAD

**Issue by cninja1** [airbnb/streamalert#964]
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.

Terraform detected that the backend type changed from "local" to "s3".

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[INFO 2019-08-11 23:44:18,106 (stream_alert_cli.terraform.handlers:94)]: Deploying Lambda Functions
[INFO 2019-08-11 23:44:18,107 (stream_alert_cli.manage_lambda.deploy:80)]: Deploying: alert alert_merger athena classifier rule
[INFO 2019-08-11 23:44:18,107 (stream_alert_cli.manage_lambda.package:68)]: Creating package for rules_engine
[INFO 2019-08-11 23:44:18,152 (stream_alert_cli.manage_lambda.package:178)]: Installing libraries: pathlib2, policyuniverse, policyuniverse==1.3.2.0, backoff==1.7.0, netaddr==0.7.19, boto3==1.9.50
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Double requirement given: policyuniverse==1.3.2.0 (already in policyuniverse, name='policyuniverse')
[ERROR 2019-08-11 23:44:18,939 (stream_alert_cli.helpers:68)]: An error occurred while running: pip install pathlib2 policyuniverse policyuniverse==1.3.2.0 backoff==1.7.0 netaddr==0.7.19 boto3==1.9.50 --upgrade --target /tmp/rules_engine
['pip', 'install', u'pathlib2', u'policyuniverse', 'policyuniverse==1.3.2.0', 'backoff==1.7.0', 'netaddr==0.7.19', 'boto3==1.9.50', '--upgrade', '--target', '/tmp/rules_engine']
[ERROR 2019-08-11 23:44:18,939 (stream_alert_cli.manage_lambda.package:77)]: Failed to install necessary libraries
None

**Comment by cninja1** [comment]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Double requirement given: policyuniverse==1.3.2.0 (already in policyuniverse, name='policyuniverse')

**Comment by gavinelder** [comment]
Hi, not a stream alert maintainer or associated with AirBNB but would like to say sorry for this. 

I surfaced this issue in https://github.com/airbnb/streamalert/pull/962. you can resolve by manually removing this line. I will PR a fix. 

Also please note that StreamAlert advises using the `stable` tag in their documentation to avoid these issues.

**Comment by ryandeivert** [comment]
thanks @gavinelder! yes, @cninja1 please follow gavin's advice :)

**Comment by cninja1** [comment]
@gavinelder @ryandeivert Thank you for your time, Will test that out.

**Comment by ryandeivert** [comment]
@gavinelder any word on a PR to fix this?
