### ISSUE TITLE
upgrade box sdk to latest version with jwt support

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#966]
## Background

When the box streamalert app was first implemented, the box sdk for python only included support for JWT auth in the v2.0.0 alpha version.

### Description

v2.0.0+ of the box sdk for python has since been officially released, and we can upgrade our requirement to remove this: https://github.com/airbnb/streamalert/blob/82d4e838900ecb0d8f630f2aad24dfcb4d4a4589/requirements-top-level.txt#L8

and tag the latest version.

## Desired Change

Upgrade box sdk and ensure things still work.

**Comment by chunyong-lin** [comment]
The release information: https://github.com/box/box-python-sdk/releases

**Comment by ryandeivert** [comment]
fixed with: https://github.com/airbnb/streamalert/pull/997
